token: ENC[AES256_GCM,data:U02xcU+GO2AzlArh9m/pi0KUf38f/dtjIvJLenj043+mPc0Znn5McA==,iv:eUNzYG0HMBdx3SPUq39rWl7fEwfWBETZbXRwB2wx2sw=,tag:6pTE3MaznBz2GY4kRdOKow==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:eu-central-1:495344428215:key/b2ffcd21-f9c5-4b17-9f0c-288c93ebb8fe
        created_at: '2020-09-06T07:24:31Z'
        enc: AQICAHh53Q5K9VQwR6IvbvoKtEIJYplzmUTR8d2WcQQL/D1JTAHiYX3gBUJMkNpHCN1BYY2XAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnq7P+l5EgYEjfKJFAgEQgDukhTGLUaGQh1brRwBJvxBeI3/Ujh22jV0McxXnK3FUpeDmOjaSyqBUO8Jmqv4ODXxbYMjkTfvo10QCVQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-06T07:25:41Z'
    mac: ENC[AES256_GCM,data:f2Ts9BpEVNUimyIStnHdWyUDvolupC0QxnSlsz3KR6nURDj7J2XoLP/8WWARc58PPU9ahfIXu7ojJXV6eTmBsoxlMXJz+ADrK8qdD+Ck0KXX1Wp+xlMtINAQ27qs2qNXI3MKYMVgnbMHzA0CqtgJwVLRWE7Rq7Yaa0SKty2fOh0=,iv:dGakQzCTR4dYDyesJkzfFTBQm0dvbvtZueQvjBaDEuc=,tag:jc2OjEnHpIJ0GSWUTnSQNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.0
