version: '3'
services:
  apollo:
    container_name: router
    build: ./router
    environment:
      - APOLLO_SCHEMA_CONFIG_EMBEDDED=true
    volumes:
      - ./supergraph.graphql:/etc/config/supergraph.graphql
    ports:
      - "80:80"
