api:
  address: 0.0.0.0
  port: 8080
graphQL:
  endpoint: https://fb-test.thesymphony.cloud/apollo/query
  authentication:
    type: BASIC
    basic:
      user: fbuser@fb.com
      password: fbuser@fb.com
cadence:
  host: fb-test.thesymphony.cloud
  port: 7933
  domain:
    name: automation
    workflowRetention: 2
    emitMetric: true
  worker:
    clientName: automation-execution-service
    serviceName: cadence-frontend
    taskList: automation-execution-task-list