version: 2
updates:
- package-ecosystem: npm
  directory: app/
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
- package-ecosystem: terraform
  directory: infra/deploy/
  schedule:
    interval: weekly
