// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
	"time"

	models1 "github.com/facebookincubator/symphony/pkg/authz/models"
	"github.com/facebookincubator/symphony/pkg/ent"
	"github.com/facebookincubator/symphony/pkg/ent/activity"
	"github.com/facebookincubator/symphony/pkg/ent/blockinstance"
	"github.com/facebookincubator/symphony/pkg/ent/checklistitem"
	"github.com/facebookincubator/symphony/pkg/ent/file"
	"github.com/facebookincubator/symphony/pkg/ent/flow"
	"github.com/facebookincubator/symphony/pkg/ent/flowinstance"
	"github.com/facebookincubator/symphony/pkg/ent/project"
	"github.com/facebookincubator/symphony/pkg/ent/schema/enum"
	"github.com/facebookincubator/symphony/pkg/ent/service"
	"github.com/facebookincubator/symphony/pkg/ent/servicetype"
	"github.com/facebookincubator/symphony/pkg/ent/surveycellscan"
	"github.com/facebookincubator/symphony/pkg/ent/user"
	"github.com/facebookincubator/symphony/pkg/ent/usersgroup"
	"github.com/facebookincubator/symphony/pkg/ent/workorder"
	"github.com/facebookincubator/symphony/pkg/exporter/models"
	"github.com/facebookincubator/symphony/pkg/flowengine/actions"
	"github.com/facebookincubator/symphony/pkg/flowengine/flowschema"
	"github.com/facebookincubator/symphony/pkg/flowengine/triggers"
)

type BlockDetails interface {
	IsBlockDetails()
}

type NamedNode interface {
	IsNamedNode()
}

type ActionBlock struct {
	ActionType    actions.ActionType               `json:"actionType"`
	Params        []*flowschema.VariableExpression `json:"params"`
	EntryPoint    *ent.EntryPoint                  `json:"entryPoint"`
	ExitPoint     *ent.ExitPoint                   `json:"exitPoint"`
	WorkOrderType *ent.WorkOrderType               `json:"workOrderType"`
	WorkerType    *ent.WorkerType                  `json:"workerType"`
}

func (ActionBlock) IsBlockDetails() {}

type ActionBlockInput struct {
	Cid              string                            `json:"cid"`
	ActionType       flowschema.ActionTypeID           `json:"actionType"`
	Params           []*VariableExpressionInput        `json:"params"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

type ActivityFilterInput struct {
	Limit          int                   `json:"limit"`
	OrderDirection ent.OrderDirection    `json:"orderDirection"`
	ActivityType   activity.ActivityType `json:"activityType"`
}

type AddBlockInstanceInput struct {
	Status  *blockinstance.Status       `json:"status"`
	Inputs  []*flowschema.VariableValue `json:"inputs"`
	Outputs []*flowschema.VariableValue `json:"outputs"`
	BlockID int                         `json:"blockId"`
}

type AddBulkServiceLinksAndPortsInput struct {
	ID      int   `json:"id"`
	PortIds []int `json:"portIds"`
	LinkIds []int `json:"linkIds"`
}

type AddComparatorInput struct {
	Name      string            `json:"name"`
	RuleLimit []*RuleLimitInput `json:"ruleLimit"`
}

type AddCounterFamilyInput struct {
	Name    string             `json:"name"`
	Counter []*AddCounterInput `json:"counter"`
}

type AddCounterInput struct {
	Name                 string                           `json:"name"`
	ExternalID           string                           `json:"externalID"`
	NetworkManagerSystem string                           `json:"networkManagerSystem"`
	Countervendorformula []*EditCounterVendorFormulaInput `json:"countervendorformula"`
}

type AddCounterVendorFormulaInput struct {
	Mandatory bool `json:"mandatory"`
	VendorFk  int  `json:"vendorFk"`
	CounterFk int  `json:"counterFk"`
	FormulaFk int  `json:"formulaFk"`
}

type AddCustomerInput struct {
	Name       string  `json:"name"`
	ExternalID *string `json:"externalId"`
}

type AddDomainInput struct {
	Name string `json:"name"`
}

type AddEquipmentInput struct {
	Name               string           `json:"name"`
	Type               int              `json:"type"`
	Location           *int             `json:"location"`
	Parent             *int             `json:"parent"`
	PositionDefinition *int             `json:"positionDefinition"`
	Properties         []*PropertyInput `json:"properties"`
	WorkOrder          *int             `json:"workOrder"`
	ExternalID         *string          `json:"externalId"`
}

type AddEquipmentPortTypeInput struct {
	Name           string                      `json:"name"`
	Properties     []*models.PropertyTypeInput `json:"properties"`
	LinkProperties []*models.PropertyTypeInput `json:"linkProperties"`
}

type AddEquipmentTypeInput struct {
	Name       string                      `json:"name"`
	Category   *string                     `json:"category"`
	Positions  []*EquipmentPositionInput   `json:"positions"`
	Ports      []*EquipmentPortInput       `json:"ports"`
	Properties []*models.PropertyTypeInput `json:"properties"`
}

type AddEventInput struct {
	Name            string       `json:"name"`
	EventTypeName   string       `json:"eventTypeName"`
	SpecificProblem string       `json:"specificProblem"`
	AdditionalInfo  string       `json:"additionalInfo"`
	Rule            []*RuleInput `json:"rule"`
	EventSeverity   int          `json:"eventSeverity"`
}

type AddEventSeverityInput struct {
	Name  string        `json:"name"`
	Event []*EventInput `json:"event"`
}

type AddFloorPlanInput struct {
	Name             string         `json:"name"`
	LocationID       int            `json:"locationID"`
	Image            *AddImageInput `json:"image"`
	ReferenceX       int            `json:"referenceX"`
	ReferenceY       int            `json:"referenceY"`
	Latitude         float64        `json:"latitude"`
	Longitude        float64        `json:"longitude"`
	ReferencePoint1x int            `json:"referencePoint1X"`
	ReferencePoint1y int            `json:"referencePoint1Y"`
	ReferencePoint2x int            `json:"referencePoint2X"`
	ReferencePoint2y int            `json:"referencePoint2Y"`
	ScaleInMeters    float64        `json:"scaleInMeters"`
}

type AddFlowDraftInput struct {
	Name                string                           `json:"name"`
	Description         *string                          `json:"description"`
	FlowID              *int                             `json:"flowID"`
	EndParamDefinitions []*flowschema.VariableDefinition `json:"endParamDefinitions"`
}

type AddFormulaInput struct {
	Name   string `json:"name"`
	Active bool   `json:"active"`
	TechFk int    `json:"techFk"`
	KpiFk  int    `json:"kpiFk"`
}

type AddHyperlinkInput struct {
	EntityType  ImageEntity `json:"entityType"`
	EntityID    int         `json:"entityId"`
	URL         string      `json:"url"`
	DisplayName *string     `json:"displayName"`
	Category    *string     `json:"category"`
}

type AddImageInput struct {
	EntityType  ImageEntity `json:"entityType"`
	EntityID    int         `json:"entityId"`
	ImgKey      string      `json:"imgKey"`
	FileName    string      `json:"fileName"`
	FileSize    int         `json:"fileSize"`
	Modified    time.Time   `json:"modified"`
	ContentType string      `json:"contentType"`
	Category    *string     `json:"category"`
	Annotation  *string     `json:"annotation"`
}

type AddKpiInput struct {
	Name     string `json:"name"`
	DomainFk int    `json:"domainFk"`
}

type AddLinkInput struct {
	Sides      []*LinkSide      `json:"sides"`
	WorkOrder  *int             `json:"workOrder"`
	Properties []*PropertyInput `json:"properties"`
	ServiceIds []int            `json:"serviceIds"`
}

type AddLocationInput struct {
	Name       string           `json:"name"`
	Type       int              `json:"type"`
	Parent     *int             `json:"parent"`
	Latitude   *float64         `json:"latitude"`
	Longitude  *float64         `json:"longitude"`
	Properties []*PropertyInput `json:"properties"`
	ExternalID *string          `json:"externalID"`
}

type AddLocationTypeInput struct {
	Name                     string                          `json:"name"`
	MapType                  *string                         `json:"mapType"`
	MapZoomLevel             *int                            `json:"mapZoomLevel"`
	IsSite                   *bool                           `json:"isSite"`
	FileCategoriesType       []*models.FileCategoryTypeInput `json:"fileCategoriesType"`
	Properties               []*models.PropertyTypeInput     `json:"properties"`
	SurveyTemplateCategories []*SurveyTemplateCategoryInput  `json:"surveyTemplateCategories"`
}

type AddPermissionsPolicyInput struct {
	Name            string                         `json:"name"`
	Description     *string                        `json:"description"`
	IsGlobal        *bool                          `json:"isGlobal"`
	InventoryInput  *models1.InventoryPolicyInput  `json:"inventoryInput"`
	WorkforceInput  *models1.WorkforcePolicyInput  `json:"workforceInput"`
	AutomationInput *models1.AutomationPolicyInput `json:"automationInput"`
	Groups          []int                          `json:"groups"`
}

type AddProjectInput struct {
	Name        string            `json:"name"`
	Description *string           `json:"description"`
	Priority    *project.Priority `json:"priority"`
	CreatorID   *int              `json:"creatorId"`
	Type        int               `json:"type"`
	Location    *int              `json:"location"`
	Properties  []*PropertyInput  `json:"properties"`
}

type AddProjectTypeInput struct {
	Name        string                      `json:"name"`
	Description *string                     `json:"description"`
	Properties  []*models.PropertyTypeInput `json:"properties"`
	WorkOrders  []*WorkOrderDefinitionInput `json:"workOrders"`
}

type AddRuleInput struct {
	Name          string            `json:"name"`
	GracePeriod   int               `json:"gracePeriod"`
	StartDateTime time.Time         `json:"startDateTime"`
	EndDateTime   time.Time         `json:"endDateTime"`
	RuleLimit     []*RuleLimitInput `json:"ruleLimit"`
	RuleType      int               `json:"ruleType"`
	Event         int               `json:"event"`
	Treshold      int               `json:"treshold"`
}

type AddRuleLimitInput struct {
	Name       string `json:"name"`
	LimitType  string `json:"limitType"`
	Comparator int    `json:"comparator"`
	Rule       int    `json:"rule"`
}

type AddRuleTypeInput struct {
	Name string `json:"name"`
}

type AddServiceEndpointInput struct {
	ID          int  `json:"id"`
	PortID      *int `json:"portId"`
	EquipmentID int  `json:"equipmentID"`
	Definition  int  `json:"definition"`
}

type AddTechInput struct {
	Name     string `json:"name"`
	DomainFk int    `json:"domainFk"`
}

type AddTresholdInput struct {
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Rule        []*RuleInput `json:"rule"`
	Kpi         *int         `json:"kpi"`
}

type AddUsersGroupInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Members     []int   `json:"members"`
	Policies    []int   `json:"policies"`
}

type AddVendorInput struct {
	Name string `json:"name"`
}

type AddWorkOrderInput struct {
	Name                string                    `json:"name"`
	Description         *string                   `json:"description"`
	WorkOrderTypeID     int                       `json:"workOrderTypeId"`
	LocationID          *int                      `json:"locationId"`
	ProjectID           *int                      `json:"projectId"`
	Properties          []*PropertyInput          `json:"properties"`
	CheckList           []*CheckListItemInput     `json:"checkList"`
	OwnerID             *int                      `json:"ownerId"`
	CheckListCategories []*CheckListCategoryInput `json:"checkListCategories"`
	AssigneeID          *int                      `json:"assigneeId"`
	Index               *int                      `json:"index"`
	Status              *workorder.Status         `json:"status"`
	Priority            *workorder.Priority       `json:"priority"`
}

type AddWorkOrderTypeInput struct {
	Name                         string                              `json:"name"`
	Description                  *string                             `json:"description"`
	Properties                   []*models.PropertyTypeInput         `json:"properties"`
	CheckListCategories          []*CheckListCategoryDefinitionInput `json:"checkListCategories"`
	AssigneeCanCompleteWorkOrder *bool                               `json:"assigneeCanCompleteWorkOrder"`
}

type AddWorkerTypeInput struct {
	Name          string                      `json:"name"`
	Description   *string                     `json:"description"`
	PropertyTypes []*models.PropertyTypeInput `json:"propertyTypes"`
}

type BlockVariableInput struct {
	BlockCid                  string                      `json:"blockCid"`
	Type                      enum.VariableExpressionType `json:"type"`
	VariableDefinitionKey     *string                     `json:"variableDefinitionKey"`
	PropertyTypeID            *int                        `json:"propertyTypeId"`
	CheckListItemDefinitionID *int                        `json:"checkListItemDefinitionId"`
}

type CheckListCategoryDefinitionInput struct {
	ID          *int                        `json:"id"`
	Title       string                      `json:"title"`
	Description *string                     `json:"description"`
	CheckList   []*CheckListDefinitionInput `json:"checkList"`
}

type CheckListCategoryInput struct {
	ID          *int                  `json:"id"`
	Title       string                `json:"title"`
	Description *string               `json:"description"`
	CheckList   []*CheckListItemInput `json:"checkList"`
}

type CheckListDefinitionInput struct {
	ID                *int                                 `json:"id"`
	Title             string                               `json:"title"`
	Type              enum.CheckListItemType               `json:"type"`
	Index             *int                                 `json:"index"`
	IsMandatory       *bool                                `json:"isMandatory"`
	EnumValues        *string                              `json:"enumValues"`
	EnumSelectionMode *enum.CheckListItemEnumSelectionMode `json:"enumSelectionMode"`
	HelpText          *string                              `json:"helpText"`
}

type CheckListItemInput struct {
	ID                 *int                                 `json:"id"`
	Title              string                               `json:"title"`
	Type               enum.CheckListItemType               `json:"type"`
	Index              *int                                 `json:"index"`
	IsMandatory        *bool                                `json:"isMandatory"`
	HelpText           *string                              `json:"helpText"`
	EnumValues         *string                              `json:"enumValues"`
	EnumSelectionMode  *enum.CheckListItemEnumSelectionMode `json:"enumSelectionMode"`
	SelectedEnumValues *string                              `json:"selectedEnumValues"`
	StringValue        *string                              `json:"stringValue"`
	Checked            *bool                                `json:"checked"`
	Files              []*FileInput                         `json:"files"`
	YesNoResponse      *checklistitem.YesNoVal              `json:"yesNoResponse"`
	WifiData           []*SurveyWiFiScanData                `json:"wifiData"`
	CellData           []*SurveyCellScanData                `json:"cellData"`
}

type ClockActivity struct {
	Author  *ent.User              `json:"author"`
	Details *activity.ClockDetails `json:"details"`
	Time    time.Time              `json:"time"`
}

type CommentInput struct {
	EntityType CommentEntity `json:"entityType"`
	ID         int           `json:"id"`
	Text       string        `json:"text"`
}

type Connector struct {
	Source *ent.ExitPoint  `json:"source"`
	Target *ent.EntryPoint `json:"target"`
}

type ConnectorInput struct {
	SourceBlockCid string           `json:"sourceBlockCid"`
	SourcePoint    *ExitPointInput  `json:"sourcePoint"`
	TargetBlockCid string           `json:"targetBlockCid"`
	TargetPoint    *EntryPointInput `json:"targetPoint"`
}

type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CounterFamilyInput struct {
	Name    string             `json:"name"`
	Counter []*AddCounterInput `json:"counter"`
}

type CounterFilterInput struct {
	FilterType    CounterFilterType   `json:"filterType"`
	Operator      enum.FilterOperator `json:"operator"`
	StringValue   *string             `json:"stringValue"`
	IDSet         []int               `json:"idSet"`
	MaxDepth      *int                `json:"maxDepth"`
	StringSet     []string            `json:"stringSet"`
	PropertyValue *CounterFamilyInput `json:"propertyValue"`
}

type CounterInput struct {
	Name                 string                           `json:"name"`
	ExternalID           string                           `json:"externalID"`
	NetworkManagerSystem string                           `json:"networkManagerSystem"`
	Countervendorformula []*EditCounterVendorFormulaInput `json:"countervendorformula"`
}

type DecisionBlock struct {
	EntryPoint       *ent.EntryPoint  `json:"entryPoint"`
	DefaultExitPoint *ent.ExitPoint   `json:"defaultExitPoint"`
	Routes           []*DecisionRoute `json:"routes"`
}

func (DecisionBlock) IsBlockDetails() {}

type DecisionBlockInput struct {
	Cid              string                            `json:"cid"`
	Routes           []*DecisionRouteInput             `json:"routes"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

type DecisionRoute struct {
	ExitPoint *ent.ExitPoint `json:"exitPoint"`
}

type DecisionRouteInput struct {
	Cid       *string                  `json:"cid"`
	Condition *VariableExpressionInput `json:"condition"`
}

type DomainInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type EditBlockInput struct {
	ID               int                               `json:"id"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

type EditComparatorInput struct {
	ID        int               `json:"id"`
	Name      string            `json:"name"`
	RuleLimit []*RuleLimitInput `json:"ruleLimit"`
}

type EditCounterFamilyInput struct {
	ID      int                 `json:"id"`
	Name    string              `json:"name"`
	Counter []*EditCounterInput `json:"counter"`
}

type EditCounterInput struct {
	ID                   int                              `json:"id"`
	Name                 string                           `json:"name"`
	ExternalID           string                           `json:"externalID"`
	NetworkManagerSystem string                           `json:"networkManagerSystem"`
	Countervendorformula []*EditCounterVendorFormulaInput `json:"countervendorformula"`
}

type EditCounterVendorFormulaInput struct {
	ID        int  `json:"id"`
	Mandatory bool `json:"mandatory"`
	VendorFk  int  `json:"vendorFk"`
	CounterFk int  `json:"counterFk"`
	FormulaFk int  `json:"formulaFk"`
}

type EditDomainInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type EditEquipmentInput struct {
	ID         int              `json:"id"`
	Name       string           `json:"name"`
	Properties []*PropertyInput `json:"properties"`
	DeviceID   *string          `json:"deviceID"`
	ExternalID *string          `json:"externalId"`
}

type EditEquipmentPortInput struct {
	Side       *LinkSide        `json:"side"`
	Properties []*PropertyInput `json:"properties"`
}

type EditEquipmentPortTypeInput struct {
	ID             int                         `json:"id"`
	Name           string                      `json:"name"`
	Properties     []*models.PropertyTypeInput `json:"properties"`
	LinkProperties []*models.PropertyTypeInput `json:"linkProperties"`
}

type EditEquipmentTypeInput struct {
	ID         int                         `json:"id"`
	Name       string                      `json:"name"`
	Category   *string                     `json:"category"`
	Positions  []*EquipmentPositionInput   `json:"positions"`
	Ports      []*EquipmentPortInput       `json:"ports"`
	Properties []*models.PropertyTypeInput `json:"properties"`
}

type EditEventInput struct {
	ID              int          `json:"id"`
	Name            string       `json:"name"`
	EventTypeName   string       `json:"eventTypeName"`
	SpecificProblem string       `json:"specificProblem"`
	AdditionalInfo  string       `json:"additionalInfo"`
	Rule            []*RuleInput `json:"rule"`
	EventSeverity   int          `json:"eventSeverity"`
}

type EditEventSeverityInput struct {
	ID    int           `json:"id"`
	Name  string        `json:"name"`
	Event []*EventInput `json:"event"`
}

type EditFormulaInput struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Active bool   `json:"active"`
	TechFk int    `json:"techFk"`
	KpiFk  int    `json:"kpiFk"`
}

type EditKpiInput struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	DomainFk int    `json:"domainFk"`
}

type EditLinkInput struct {
	ID         int              `json:"id"`
	Properties []*PropertyInput `json:"properties"`
	ServiceIds []int            `json:"serviceIds"`
}

type EditLocationInput struct {
	ID         int              `json:"id"`
	Name       string           `json:"name"`
	Latitude   float64          `json:"latitude"`
	Longitude  float64          `json:"longitude"`
	Properties []*PropertyInput `json:"properties"`
	ExternalID *string          `json:"externalID"`
}

type EditLocationTypeInput struct {
	ID                 int                             `json:"id"`
	Name               string                          `json:"name"`
	MapType            *string                         `json:"mapType"`
	MapZoomLevel       *int                            `json:"mapZoomLevel"`
	IsSite             *bool                           `json:"isSite"`
	FileCategoriesType []*models.FileCategoryTypeInput `json:"fileCategoriesType"`
	Properties         []*models.PropertyTypeInput     `json:"properties"`
}

type EditPermissionsPolicyInput struct {
	ID              int                            `json:"id"`
	Name            *string                        `json:"name"`
	Description     *string                        `json:"description"`
	IsGlobal        *bool                          `json:"isGlobal"`
	InventoryInput  *models1.InventoryPolicyInput  `json:"inventoryInput"`
	WorkforceInput  *models1.WorkforcePolicyInput  `json:"workforceInput"`
	AutomationInput *models1.AutomationPolicyInput `json:"automationInput"`
	Groups          []int                          `json:"groups"`
}

type EditProjectInput struct {
	ID          int               `json:"id"`
	Name        string            `json:"name"`
	Description *string           `json:"description"`
	Priority    *project.Priority `json:"priority"`
	CreatorID   *int              `json:"creatorId"`
	Type        int               `json:"type"`
	Location    *int              `json:"location"`
	Properties  []*PropertyInput  `json:"properties"`
}

type EditProjectTypeInput struct {
	ID          int                         `json:"id"`
	Name        string                      `json:"name"`
	Description *string                     `json:"description"`
	Properties  []*models.PropertyTypeInput `json:"properties"`
	WorkOrders  []*WorkOrderDefinitionInput `json:"workOrders"`
}

type EditReportFilterInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type EditRuleInput struct {
	ID            int               `json:"id"`
	Name          string            `json:"name"`
	GracePeriod   *int              `json:"gracePeriod"`
	StartDateTime *time.Time        `json:"startDateTime"`
	EndDateTime   *time.Time        `json:"endDateTime"`
	RuleLimit     []*RuleLimitInput `json:"ruleLimit"`
	RuleType      int               `json:"ruleType"`
	Event         int               `json:"event"`
	Treshold      int               `json:"treshold"`
}

type EditRuleLimitInput struct {
	ID         int    `json:"id"`
	Name       string `json:"name"`
	LimitType  string `json:"limitType"`
	Comparator int    `json:"comparator"`
	Rule       int    `json:"rule"`
}

type EditRuleTypeInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type EditTechInput struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	DomainFk int    `json:"domainFk"`
}

type EditTresholdInput struct {
	ID          int          `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Rule        []*RuleInput `json:"rule"`
}

type EditUserInput struct {
	ID           int                `json:"id"`
	FirstName    *string            `json:"firstName"`
	LastName     *string            `json:"lastName"`
	Status       *user.Status       `json:"status"`
	Role         *user.Role         `json:"role"`
	DistanceUnit *user.DistanceUnit `json:"distanceUnit"`
}

type EditUsersGroupInput struct {
	ID          int                `json:"id"`
	Name        *string            `json:"name"`
	Description *string            `json:"description"`
	Status      *usersgroup.Status `json:"status"`
	Members     []int              `json:"members"`
	Policies    []int              `json:"policies"`
}

type EditVendorInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type EditWorkOrderInput struct {
	ID                  int                       `json:"id"`
	Name                string                    `json:"name"`
	Description         *string                   `json:"description"`
	OwnerID             *int                      `json:"ownerId"`
	InstallDate         *time.Time                `json:"installDate"`
	AssigneeID          *int                      `json:"assigneeId"`
	Index               *int                      `json:"index"`
	Status              *workorder.Status         `json:"status"`
	Priority            *workorder.Priority       `json:"priority"`
	ProjectID           *int                      `json:"projectId"`
	Properties          []*PropertyInput          `json:"properties"`
	CheckList           []*CheckListItemInput     `json:"checkList"`
	CheckListCategories []*CheckListCategoryInput `json:"checkListCategories"`
	LocationID          *int                      `json:"locationId"`
}

type EditWorkOrderTypeInput struct {
	ID                           int                                 `json:"id"`
	Name                         string                              `json:"name"`
	Description                  *string                             `json:"description"`
	Properties                   []*models.PropertyTypeInput         `json:"properties"`
	CheckListCategories          []*CheckListCategoryDefinitionInput `json:"checkListCategories"`
	AssigneeCanCompleteWorkOrder *bool                               `json:"assigneeCanCompleteWorkOrder"`
}

type EditWorkerTypeInput struct {
	ID            int                         `json:"id"`
	Name          string                      `json:"name"`
	Description   *string                     `json:"description"`
	PropertyTypes []*models.PropertyTypeInput `json:"propertyTypes"`
}

type EndBlock struct {
	Params     []*flowschema.VariableExpression `json:"params"`
	EntryPoint *ent.EntryPoint                  `json:"entryPoint"`
}

func (EndBlock) IsBlockDetails() {}

type EndBlockInput struct {
	Cid              string                            `json:"cid"`
	Params           []*VariableExpressionInput        `json:"params"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

// End To End Path Descovery.
type EndToEndPath struct {
	// The links in the path
	Links []*ent.Link `json:"links"`
	// The start,end ports in the path
	Ports []*ent.EquipmentPort `json:"ports"`
}

type EntryPointInput struct {
	Role *flowschema.EntryPointRole `json:"role"`
	Cid  *string                    `json:"cid"`
}

type EquipmentPortConnectionInput struct {
	ID   *int    `json:"id"`
	Name *string `json:"name"`
}

type EquipmentPortInput struct {
	ID             *int                            `json:"id"`
	Name           string                          `json:"name"`
	Index          *int                            `json:"index"`
	VisibleLabel   *string                         `json:"visibleLabel"`
	PortTypeID     *int                            `json:"portTypeID"`
	Bandwidth      *string                         `json:"bandwidth"`
	ConnectedPorts []*EquipmentPortConnectionInput `json:"connectedPorts"`
}

type EquipmentPositionInput struct {
	ID           *int    `json:"id"`
	Name         string  `json:"name"`
	Index        *int    `json:"index"`
	VisibleLabel *string `json:"visibleLabel"`
}

type EventInput struct {
	Name            string       `json:"name"`
	EventTypeName   string       `json:"eventTypeName"`
	SpecificProblem string       `json:"specificProblem"`
	AdditionalInfo  string       `json:"additionalInfo"`
	Rule            []*RuleInput `json:"rule"`
	EventSeverity   *int         `json:"eventSeverity"`
}

type ExitPointInput struct {
	Role *flowschema.ExitPointRole `json:"role"`
	Cid  *string                   `json:"cid"`
}

type FileInput struct {
	ID               *int       `json:"id"`
	FileName         string     `json:"fileName"`
	SizeInBytes      *int       `json:"sizeInBytes"`
	ModificationTime *int       `json:"modificationTime"`
	UploadTime       *int       `json:"uploadTime"`
	FileType         *file.Type `json:"fileType"`
	MimeType         *string    `json:"mimeType"`
	StoreKey         string     `json:"storeKey"`
	Annotation       *string    `json:"annotation"`
}

type GeneralFilter struct {
	FilterType    string              `json:"filterType"`
	Key           string              `json:"key"`
	Operator      enum.FilterOperator `json:"operator"`
	StringValue   *string             `json:"stringValue"`
	IDSet         []int               `json:"idSet"`
	StringSet     []string            `json:"stringSet"`
	BoolValue     *bool               `json:"boolValue"`
	PropertyValue *ent.PropertyType   `json:"propertyValue"`
}

type GeneralFilterInput struct {
	FilterType    string                    `json:"filterType"`
	Key           string                    `json:"key"`
	Operator      enum.FilterOperator       `json:"operator"`
	StringValue   *string                   `json:"stringValue"`
	IDSet         []int                     `json:"idSet"`
	StringSet     []string                  `json:"stringSet"`
	BoolValue     *bool                     `json:"boolValue"`
	PropertyValue *models.PropertyTypeInput `json:"propertyValue"`
}

type GotoBlock struct {
	Target     *ent.Block      `json:"target"`
	EntryPoint *ent.EntryPoint `json:"entryPoint"`
}

func (GotoBlock) IsBlockDetails() {}

type GotoBlockInput struct {
	Cid              string                            `json:"cid"`
	TargetBlockCid   *string                           `json:"targetBlockCid"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

type ImportFlowDraftInput struct {
	ID                  int                              `json:"id"`
	Name                string                           `json:"name"`
	Description         *string                          `json:"description"`
	EndParamDefinitions []*flowschema.VariableDefinition `json:"endParamDefinitions"`
	StartBlock          *StartBlockInput                 `json:"startBlock"`
	EndBlocks           []*EndBlockInput                 `json:"endBlocks"`
	DecisionBlocks      []*DecisionBlockInput            `json:"decisionBlocks"`
	GotoBlocks          []*GotoBlockInput                `json:"gotoBlocks"`
	SubflowBlocks       []*SubflowBlockInput             `json:"subflowBlocks"`
	TriggerBlocks       []*TriggerBlockInput             `json:"triggerBlocks"`
	ActionBlocks        []*ActionBlockInput              `json:"actionBlocks"`
	TrueFalseBlocks     []*TrueFalseBlockInput           `json:"trueFalseBlocks"`
	Connectors          []*ConnectorInput                `json:"connectors"`
}

type KpiFilterInput struct {
	FilterType  KpiFilterType       `json:"filterType"`
	Operator    enum.FilterOperator `json:"operator"`
	StringValue *string             `json:"stringValue"`
	IDSet       []int               `json:"idSet"`
	MaxDepth    *int                `json:"maxDepth"`
	StringSet   []string            `json:"stringSet"`
}

type LatestPythonPackageResult struct {
	LastPythonPackage         *PythonPackage `json:"lastPythonPackage"`
	LastBreakingPythonPackage *PythonPackage `json:"lastBreakingPythonPackage"`
}

type LinkSide struct {
	Equipment int `json:"equipment"`
	Port      int `json:"port"`
}

type LocationTypeIndex struct {
	LocationTypeID int `json:"locationTypeID"`
	Index          int `json:"index"`
}

type NetworkTopology struct {
	Nodes []ent.Noder     `json:"nodes"`
	Links []*TopologyLink `json:"links"`
}

type PermissionsPolicyFilterInput struct {
	FilterType  PermissionsPolicyFilterType `json:"filterType"`
	Operator    enum.FilterOperator         `json:"operator"`
	StringValue *string                     `json:"stringValue"`
	MaxDepth    *int                        `json:"maxDepth"`
}

type PermissionsPolicySearchResult struct {
	PermissionsPolicies []*ent.PermissionsPolicy `json:"permissionsPolicies"`
	Count               int                      `json:"count"`
}

type ProjectFilterInput struct {
	FilterType    ProjectFilterType         `json:"filterType"`
	Operator      enum.FilterOperator       `json:"operator"`
	StringValue   *string                   `json:"stringValue"`
	IDSet         []int                     `json:"idSet"`
	MaxDepth      *int                      `json:"maxDepth"`
	StringSet     []string                  `json:"stringSet"`
	PropertyValue *models.PropertyTypeInput `json:"propertyValue"`
}

type PropertyInput struct {
	ID                 *int     `json:"id"`
	PropertyTypeID     int      `json:"propertyTypeID"`
	StringValue        *string  `json:"stringValue"`
	IntValue           *int     `json:"intValue"`
	BooleanValue       *bool    `json:"booleanValue"`
	FloatValue         *float64 `json:"floatValue"`
	LatitudeValue      *float64 `json:"latitudeValue"`
	LongitudeValue     *float64 `json:"longitudeValue"`
	RangeFromValue     *float64 `json:"rangeFromValue"`
	RangeToValue       *float64 `json:"rangeToValue"`
	NodeIDValue        *int     `json:"nodeIDValue"`
	IsEditable         *bool    `json:"isEditable"`
	IsInstanceProperty *bool    `json:"isInstanceProperty"`
}

type PublishFlowInput struct {
	FlowDraftID         int                     `json:"flowDraftID"`
	FlowInstancesPolicy flow.NewInstancesPolicy `json:"flowInstancesPolicy"`
}

type PythonPackage struct {
	Version           string    `json:"version"`
	WhlFileKey        string    `json:"whlFileKey"`
	UploadTime        time.Time `json:"uploadTime"`
	HasBreakingChange bool      `json:"hasBreakingChange"`
}

type ReportFilterInput struct {
	Name    string                `json:"name"`
	Entity  FilterEntity          `json:"entity"`
	Filters []*GeneralFilterInput `json:"filters"`
}

type RuleInput struct {
	Name          string            `json:"name"`
	GracePeriod   *int              `json:"gracePeriod"`
	StartDateTime *time.Time        `json:"startDateTime"`
	EndDateTime   *time.Time        `json:"endDateTime"`
	RuleLimit     []*RuleLimitInput `json:"ruleLimit"`
}

type RuleLimitInput struct {
	Name       string `json:"name"`
	LimitType  string `json:"limitType"`
	Comparator int    `json:"comparator"`
	Rule       int    `json:"rule"`
}

type SearchEntry struct {
	EntityID   int     `json:"entityId"`
	EntityType string  `json:"entityType"`
	Name       string  `json:"name"`
	Type       string  `json:"type"`
	ExternalID *string `json:"externalId"`
}

// A search node edge in a connection.
type SearchNodeEdge struct {
	// The search node at the end of the edge.
	Node ent.Noder `json:"node"`
	// A cursor for use in pagination.
	Cursor ent.Cursor `json:"cursor"`
}

// A connection to a list of search nodes.
type SearchNodesConnection struct {
	// Total count of search nodes in all pages.
	TotalCount int `json:"totalCount"`
	// A list of search node edges.
	Edges []*SearchNodeEdge `json:"edges"`
	// Information to aid in pagination.
	PageInfo *ent.PageInfo `json:"pageInfo"`
}

type ServiceCreateData struct {
	Name               string           `json:"name"`
	ExternalID         *string          `json:"externalId"`
	Status             service.Status   `json:"status"`
	ServiceTypeID      int              `json:"serviceTypeId"`
	CustomerID         *int             `json:"customerId"`
	UpstreamServiceIds []int            `json:"upstreamServiceIds"`
	Properties         []*PropertyInput `json:"properties"`
}

type ServiceEditData struct {
	ID                 int              `json:"id"`
	Name               *string          `json:"name"`
	ExternalID         *string          `json:"externalId"`
	Status             *service.Status  `json:"status"`
	CustomerID         *int             `json:"customerId"`
	UpstreamServiceIds []int            `json:"upstreamServiceIds"`
	Properties         []*PropertyInput `json:"properties"`
}

type ServiceEndpointDefinitionInput struct {
	ID              *int    `json:"id"`
	Name            string  `json:"name"`
	Role            *string `json:"role"`
	Index           int     `json:"index"`
	EquipmentTypeID int     `json:"equipmentTypeID"`
}

type ServiceTypeCreateData struct {
	Name            string                            `json:"name"`
	HasCustomer     bool                              `json:"hasCustomer"`
	Properties      []*models.PropertyTypeInput       `json:"properties"`
	Endpoints       []*ServiceEndpointDefinitionInput `json:"endpoints"`
	DiscoveryMethod *servicetype.DiscoveryMethod      `json:"discoveryMethod"`
}

type ServiceTypeEditData struct {
	ID          int                               `json:"id"`
	Name        string                            `json:"name"`
	HasCustomer bool                              `json:"hasCustomer"`
	Properties  []*models.PropertyTypeInput       `json:"properties"`
	Endpoints   []*ServiceEndpointDefinitionInput `json:"endpoints"`
}

type StartBlock struct {
	ParamDefinitions []*flowschema.VariableDefinition `json:"paramDefinitions"`
	ExitPoint        *ent.ExitPoint                   `json:"exitPoint"`
}

func (StartBlock) IsBlockDetails() {}

type StartBlockInput struct {
	Cid              string                            `json:"cid"`
	ParamDefinitions []*flowschema.VariableDefinition  `json:"paramDefinitions"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

type StartFlowInput struct {
	FlowID int                         `json:"flowID"`
	Params []*flowschema.VariableValue `json:"params"`
}

type SubflowBlock struct {
	Flow       *ent.Flow                        `json:"flow"`
	Params     []*flowschema.VariableExpression `json:"params"`
	EntryPoint *ent.EntryPoint                  `json:"entryPoint"`
	ExitPoint  *ent.ExitPoint                   `json:"exitPoint"`
}

func (SubflowBlock) IsBlockDetails() {}

type SubflowBlockInput struct {
	Cid              string                            `json:"cid"`
	FlowID           int                               `json:"flowId"`
	Params           []*VariableExpressionInput        `json:"params"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

type SurveyCellScanData struct {
	NetworkType           surveycellscan.NetworkType `json:"networkType"`
	SignalStrength        int                        `json:"signalStrength"`
	Timestamp             *int                       `json:"timestamp"`
	BaseStationID         *string                    `json:"baseStationID"`
	NetworkID             *string                    `json:"networkID"`
	SystemID              *string                    `json:"systemID"`
	CellID                *string                    `json:"cellID"`
	LocationAreaCode      *string                    `json:"locationAreaCode"`
	MobileCountryCode     *string                    `json:"mobileCountryCode"`
	MobileNetworkCode     *string                    `json:"mobileNetworkCode"`
	PrimaryScramblingCode *string                    `json:"primaryScramblingCode"`
	Operator              *string                    `json:"operator"`
	Arfcn                 *int                       `json:"arfcn"`
	PhysicalCellID        *string                    `json:"physicalCellID"`
	TrackingAreaCode      *string                    `json:"trackingAreaCode"`
	TimingAdvance         *int                       `json:"timingAdvance"`
	Earfcn                *int                       `json:"earfcn"`
	Uarfcn                *int                       `json:"uarfcn"`
	Latitude              *float64                   `json:"latitude"`
	Longitude             *float64                   `json:"longitude"`
	Altitude              *float64                   `json:"altitude"`
	Heading               *float64                   `json:"heading"`
	Rssi                  *float64                   `json:"rssi"`
}

type SurveyCreateData struct {
	Name                string                    `json:"name"`
	OwnerName           *string                   `json:"ownerName"`
	CreationTimestamp   *int                      `json:"creationTimestamp"`
	CompletionTimestamp int                       `json:"completionTimestamp"`
	Status              *SurveyStatus             `json:"status"`
	LocationID          int                       `json:"locationID"`
	SurveyResponses     []*SurveyQuestionResponse `json:"surveyResponses"`
}

type SurveyQuestionResponse struct {
	FormName         *string               `json:"formName"`
	FormDescription  *string               `json:"formDescription"`
	FormIndex        int                   `json:"formIndex"`
	QuestionFormat   *SurveyQuestionType   `json:"questionFormat"`
	QuestionText     string                `json:"questionText"`
	QuestionIndex    int                   `json:"questionIndex"`
	BoolData         *bool                 `json:"boolData"`
	EmailData        *string               `json:"emailData"`
	Latitude         *float64              `json:"latitude"`
	Longitude        *float64              `json:"longitude"`
	LocationAccuracy *float64              `json:"locationAccuracy"`
	Altitude         *float64              `json:"altitude"`
	PhoneData        *string               `json:"phoneData"`
	TextData         *string               `json:"textData"`
	FloatData        *float64              `json:"floatData"`
	IntData          *int                  `json:"intData"`
	DateData         *int                  `json:"dateData"`
	PhotoData        *FileInput            `json:"photoData"`
	WifiData         []*SurveyWiFiScanData `json:"wifiData"`
	CellData         []*SurveyCellScanData `json:"cellData"`
	ImagesData       []*FileInput          `json:"imagesData"`
}

type SurveyTemplateCategoryInput struct {
	ID                      *int                           `json:"id"`
	CategoryTitle           string                         `json:"categoryTitle"`
	CategoryDescription     string                         `json:"categoryDescription"`
	SurveyTemplateQuestions []*SurveyTemplateQuestionInput `json:"surveyTemplateQuestions"`
}

type SurveyTemplateQuestionInput struct {
	ID                  *int               `json:"id"`
	QuestionTitle       string             `json:"questionTitle"`
	QuestionDescription string             `json:"questionDescription"`
	QuestionType        SurveyQuestionType `json:"questionType"`
	Index               int                `json:"index"`
}

type SurveyWiFiScanData struct {
	Timestamp    int      `json:"timestamp"`
	Frequency    int      `json:"frequency"`
	Channel      int      `json:"channel"`
	Bssid        string   `json:"bssid"`
	Strength     int      `json:"strength"`
	Ssid         *string  `json:"ssid"`
	Band         *string  `json:"band"`
	ChannelWidth *int     `json:"channelWidth"`
	Capabilities *string  `json:"capabilities"`
	Latitude     *float64 `json:"latitude"`
	Longitude    *float64 `json:"longitude"`
	Altitude     *float64 `json:"altitude"`
	Heading      *float64 `json:"heading"`
	Rssi         *float64 `json:"rssi"`
}

type TechnicianCheckListItemInput struct {
	ID                 int                     `json:"id"`
	SelectedEnumValues *string                 `json:"selectedEnumValues"`
	StringValue        *string                 `json:"stringValue"`
	Checked            *bool                   `json:"checked"`
	YesNoResponse      *checklistitem.YesNoVal `json:"yesNoResponse"`
	WifiData           []*SurveyWiFiScanData   `json:"wifiData"`
	CellData           []*SurveyCellScanData   `json:"cellData"`
	FilesData          []*FileInput            `json:"filesData"`
}

type TechnicianWorkOrderCheckInInput struct {
	DistanceMeters *float64   `json:"distanceMeters"`
	CheckInTime    *time.Time `json:"checkInTime"`
}

type TechnicianWorkOrderCheckOutInput struct {
	WorkOrderID         int                       `json:"workOrderId"`
	Reason              activity.ClockOutReason   `json:"reason"`
	CheckListCategories []*CheckListCategoryInput `json:"checkListCategories"`
	Comment             *string                   `json:"comment"`
	DistanceMeters      *float64                  `json:"distanceMeters"`
	CheckOutTime        *time.Time                `json:"checkOutTime"`
}

type TechnicianWorkOrderUploadInput struct {
	WorkOrderID         int                       `json:"workOrderId"`
	CheckListCategories []*CheckListCategoryInput `json:"checkListCategories"`
}

type TopologyLink struct {
	Type   TopologyLinkType `json:"type"`
	Source ent.Noder        `json:"source"`
	Target ent.Noder        `json:"target"`
}

type TresholdInput struct {
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Rule        []*RuleInput `json:"rule"`
	Kpi         *int         `json:"kpi"`
}

type TriggerBlock struct {
	TriggerType triggers.TriggerType             `json:"triggerType"`
	Params      []*flowschema.VariableExpression `json:"params"`
	ExitPoint   *ent.ExitPoint                   `json:"exitPoint"`
}

func (TriggerBlock) IsBlockDetails() {}

type TriggerBlockInput struct {
	Cid              string                            `json:"cid"`
	TriggerType      flowschema.TriggerTypeID          `json:"triggerType"`
	Params           []*VariableExpressionInput        `json:"params"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

type TrueFalseBlock struct {
	EntryPoint     *ent.EntryPoint `json:"entryPoint"`
	TrueExitPoint  *ent.ExitPoint  `json:"trueExitPoint"`
	FalseExitPoint *ent.ExitPoint  `json:"falseExitPoint"`
}

func (TrueFalseBlock) IsBlockDetails() {}

type TrueFalseBlockInput struct {
	Cid              string                            `json:"cid"`
	UIRepresentation *flowschema.BlockUIRepresentation `json:"uiRepresentation"`
}

type UpdateUserGroupsInput struct {
	ID             int   `json:"id"`
	AddGroupIds    []int `json:"addGroupIds"`
	RemoveGroupIds []int `json:"removeGroupIds"`
}

type UserFilterInput struct {
	FilterType    UserFilterType            `json:"filterType"`
	Operator      enum.FilterOperator       `json:"operator"`
	StringValue   *string                   `json:"stringValue"`
	PropertyValue *models.PropertyTypeInput `json:"propertyValue"`
	StatusValue   *user.Status              `json:"statusValue"`
	IDSet         []int                     `json:"idSet"`
	StringSet     []string                  `json:"stringSet"`
	MaxDepth      *int                      `json:"maxDepth"`
}

type UserSearchResult struct {
	Users []*ent.User `json:"users"`
	Count int         `json:"count"`
}

type UsersGroupFilterInput struct {
	FilterType  UsersGroupFilterType `json:"filterType"`
	Operator    enum.FilterOperator  `json:"operator"`
	StringValue *string              `json:"stringValue"`
	MaxDepth    *int                 `json:"maxDepth"`
}

type UsersGroupSearchResult struct {
	UsersGroups []*ent.UsersGroup `json:"usersGroups"`
	Count       int               `json:"count"`
}

type VariableExpressionInput struct {
	Type                  enum.VariableExpressionType `json:"type"`
	VariableDefinitionKey *string                     `json:"variableDefinitionKey"`
	PropertyTypeID        *int                        `json:"propertyTypeId"`
	Expression            string                      `json:"expression"`
	BlockVariables        []*BlockVariableInput       `json:"blockVariables"`
}

type WorkOrderDefinitionInput struct {
	ID    *int `json:"id"`
	Index *int `json:"index"`
	Type  int  `json:"type"`
}

type WorkOrderExecutionResult struct {
	ID               int              `json:"id"`
	Name             string           `json:"name"`
	EquipmentAdded   []*ent.Equipment `json:"equipmentAdded"`
	EquipmentRemoved []int            `json:"equipmentRemoved"`
	LinkAdded        []*ent.Link      `json:"linkAdded"`
	LinkRemoved      []int            `json:"linkRemoved"`
}

type CommentEntity string

const (
	CommentEntityWorkOrder CommentEntity = "WORK_ORDER"
	CommentEntityProject   CommentEntity = "PROJECT"
)

var AllCommentEntity = []CommentEntity{
	CommentEntityWorkOrder,
	CommentEntityProject,
}

func (e CommentEntity) IsValid() bool {
	switch e {
	case CommentEntityWorkOrder, CommentEntityProject:
		return true
	}
	return false
}

func (e CommentEntity) String() string {
	return string(e)
}

func (e *CommentEntity) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentEntity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentEntity", str)
	}
	return nil
}

func (e CommentEntity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type CounterFilterType string

const (
	CounterFilterTypeName CounterFilterType = "NAME"
)

var AllCounterFilterType = []CounterFilterType{
	CounterFilterTypeName,
}

func (e CounterFilterType) IsValid() bool {
	switch e {
	case CounterFilterTypeName:
		return true
	}
	return false
}

func (e CounterFilterType) String() string {
	return string(e)
}

func (e *CounterFilterType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CounterFilterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CounterFilterType", str)
	}
	return nil
}

func (e CounterFilterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FilterEntity string

const (
	FilterEntityWorkOrder FilterEntity = "WORK_ORDER"
	FilterEntityPort      FilterEntity = "PORT"
	FilterEntityEquipment FilterEntity = "EQUIPMENT"
	FilterEntityLink      FilterEntity = "LINK"
	FilterEntityLocation  FilterEntity = "LOCATION"
	FilterEntityService   FilterEntity = "SERVICE"
)

var AllFilterEntity = []FilterEntity{
	FilterEntityWorkOrder,
	FilterEntityPort,
	FilterEntityEquipment,
	FilterEntityLink,
	FilterEntityLocation,
	FilterEntityService,
}

func (e FilterEntity) IsValid() bool {
	switch e {
	case FilterEntityWorkOrder, FilterEntityPort, FilterEntityEquipment, FilterEntityLink, FilterEntityLocation, FilterEntityService:
		return true
	}
	return false
}

func (e FilterEntity) String() string {
	return string(e)
}

func (e *FilterEntity) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilterEntity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilterEntity", str)
	}
	return nil
}

func (e FilterEntity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ImageEntity string

const (
	ImageEntityLocation      ImageEntity = "LOCATION"
	ImageEntityWorkOrder     ImageEntity = "WORK_ORDER"
	ImageEntitySiteSurvey    ImageEntity = "SITE_SURVEY"
	ImageEntityEquipment     ImageEntity = "EQUIPMENT"
	ImageEntityUser          ImageEntity = "USER"
	ImageEntityChecklistItem ImageEntity = "CHECKLIST_ITEM"
)

var AllImageEntity = []ImageEntity{
	ImageEntityLocation,
	ImageEntityWorkOrder,
	ImageEntitySiteSurvey,
	ImageEntityEquipment,
	ImageEntityUser,
	ImageEntityChecklistItem,
}

func (e ImageEntity) IsValid() bool {
	switch e {
	case ImageEntityLocation, ImageEntityWorkOrder, ImageEntitySiteSurvey, ImageEntityEquipment, ImageEntityUser, ImageEntityChecklistItem:
		return true
	}
	return false
}

func (e ImageEntity) String() string {
	return string(e)
}

func (e *ImageEntity) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImageEntity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImageEntity", str)
	}
	return nil
}

func (e ImageEntity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type KpiFilterType string

const (
	KpiFilterTypeName KpiFilterType = "NAME"
)

var AllKpiFilterType = []KpiFilterType{
	KpiFilterTypeName,
}

func (e KpiFilterType) IsValid() bool {
	switch e {
	case KpiFilterTypeName:
		return true
	}
	return false
}

func (e KpiFilterType) String() string {
	return string(e)
}

func (e *KpiFilterType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KpiFilterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KpiFilterType", str)
	}
	return nil
}

func (e KpiFilterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// what filters should we apply on permissionsPolicy
type PermissionsPolicyFilterType string

const (
	PermissionsPolicyFilterTypePermissionsPolicyName PermissionsPolicyFilterType = "PERMISSIONS_POLICY_NAME"
)

var AllPermissionsPolicyFilterType = []PermissionsPolicyFilterType{
	PermissionsPolicyFilterTypePermissionsPolicyName,
}

func (e PermissionsPolicyFilterType) IsValid() bool {
	switch e {
	case PermissionsPolicyFilterTypePermissionsPolicyName:
		return true
	}
	return false
}

func (e PermissionsPolicyFilterType) String() string {
	return string(e)
}

func (e *PermissionsPolicyFilterType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PermissionsPolicyFilterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PermissionsPolicyFilterType", str)
	}
	return nil
}

func (e PermissionsPolicyFilterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ProjectFilterType string

const (
	ProjectFilterTypeProjectName     ProjectFilterType = "PROJECT_NAME"
	ProjectFilterTypeProjectOwnedBy  ProjectFilterType = "PROJECT_OWNED_BY"
	ProjectFilterTypeProjectType     ProjectFilterType = "PROJECT_TYPE"
	ProjectFilterTypeLocationInst    ProjectFilterType = "LOCATION_INST"
	ProjectFilterTypeProjectPriority ProjectFilterType = "PROJECT_PRIORITY"
	ProjectFilterTypeProperty        ProjectFilterType = "PROPERTY"
)

var AllProjectFilterType = []ProjectFilterType{
	ProjectFilterTypeProjectName,
	ProjectFilterTypeProjectOwnedBy,
	ProjectFilterTypeProjectType,
	ProjectFilterTypeLocationInst,
	ProjectFilterTypeProjectPriority,
	ProjectFilterTypeProperty,
}

func (e ProjectFilterType) IsValid() bool {
	switch e {
	case ProjectFilterTypeProjectName, ProjectFilterTypeProjectOwnedBy, ProjectFilterTypeProjectType, ProjectFilterTypeLocationInst, ProjectFilterTypeProjectPriority, ProjectFilterTypeProperty:
		return true
	}
	return false
}

func (e ProjectFilterType) String() string {
	return string(e)
}

func (e *ProjectFilterType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectFilterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectFilterType", str)
	}
	return nil
}

func (e ProjectFilterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SurveyQuestionType string

const (
	SurveyQuestionTypeBool     SurveyQuestionType = "BOOL"
	SurveyQuestionTypeEmail    SurveyQuestionType = "EMAIL"
	SurveyQuestionTypeCoords   SurveyQuestionType = "COORDS"
	SurveyQuestionTypePhone    SurveyQuestionType = "PHONE"
	SurveyQuestionTypeText     SurveyQuestionType = "TEXT"
	SurveyQuestionTypeTextarea SurveyQuestionType = "TEXTAREA"
	SurveyQuestionTypePhoto    SurveyQuestionType = "PHOTO"
	SurveyQuestionTypeWifi     SurveyQuestionType = "WIFI"
	SurveyQuestionTypeCellular SurveyQuestionType = "CELLULAR"
	SurveyQuestionTypeFloat    SurveyQuestionType = "FLOAT"
	SurveyQuestionTypeInteger  SurveyQuestionType = "INTEGER"
	SurveyQuestionTypeDate     SurveyQuestionType = "DATE"
)

var AllSurveyQuestionType = []SurveyQuestionType{
	SurveyQuestionTypeBool,
	SurveyQuestionTypeEmail,
	SurveyQuestionTypeCoords,
	SurveyQuestionTypePhone,
	SurveyQuestionTypeText,
	SurveyQuestionTypeTextarea,
	SurveyQuestionTypePhoto,
	SurveyQuestionTypeWifi,
	SurveyQuestionTypeCellular,
	SurveyQuestionTypeFloat,
	SurveyQuestionTypeInteger,
	SurveyQuestionTypeDate,
}

func (e SurveyQuestionType) IsValid() bool {
	switch e {
	case SurveyQuestionTypeBool, SurveyQuestionTypeEmail, SurveyQuestionTypeCoords, SurveyQuestionTypePhone, SurveyQuestionTypeText, SurveyQuestionTypeTextarea, SurveyQuestionTypePhoto, SurveyQuestionTypeWifi, SurveyQuestionTypeCellular, SurveyQuestionTypeFloat, SurveyQuestionTypeInteger, SurveyQuestionTypeDate:
		return true
	}
	return false
}

func (e SurveyQuestionType) String() string {
	return string(e)
}

func (e *SurveyQuestionType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SurveyQuestionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SurveyQuestionType", str)
	}
	return nil
}

func (e SurveyQuestionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SurveyStatus string

const (
	SurveyStatusPlanned    SurveyStatus = "PLANNED"
	SurveyStatusInprogress SurveyStatus = "INPROGRESS"
	SurveyStatusCompleted  SurveyStatus = "COMPLETED"
)

var AllSurveyStatus = []SurveyStatus{
	SurveyStatusPlanned,
	SurveyStatusInprogress,
	SurveyStatusCompleted,
}

func (e SurveyStatus) IsValid() bool {
	switch e {
	case SurveyStatusPlanned, SurveyStatusInprogress, SurveyStatusCompleted:
		return true
	}
	return false
}

func (e SurveyStatus) String() string {
	return string(e)
}

func (e *SurveyStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SurveyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SurveyStatus", str)
	}
	return nil
}

func (e SurveyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TopologyLinkType string

const (
	TopologyLinkTypePhysical TopologyLinkType = "PHYSICAL"
)

var AllTopologyLinkType = []TopologyLinkType{
	TopologyLinkTypePhysical,
}

func (e TopologyLinkType) IsValid() bool {
	switch e {
	case TopologyLinkTypePhysical:
		return true
	}
	return false
}

func (e TopologyLinkType) String() string {
	return string(e)
}

func (e *TopologyLinkType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TopologyLinkType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TopologyLinkType", str)
	}
	return nil
}

func (e TopologyLinkType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// what filters should we apply on users
type UserFilterType string

const (
	UserFilterTypeUserName   UserFilterType = "USER_NAME"
	UserFilterTypeUserStatus UserFilterType = "USER_STATUS"
)

var AllUserFilterType = []UserFilterType{
	UserFilterTypeUserName,
	UserFilterTypeUserStatus,
}

func (e UserFilterType) IsValid() bool {
	switch e {
	case UserFilterTypeUserName, UserFilterTypeUserStatus:
		return true
	}
	return false
}

func (e UserFilterType) String() string {
	return string(e)
}

func (e *UserFilterType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserFilterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserFilterType", str)
	}
	return nil
}

func (e UserFilterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// what filters should we apply on usersGroups
type UsersGroupFilterType string

const (
	UsersGroupFilterTypeGroupName UsersGroupFilterType = "GROUP_NAME"
)

var AllUsersGroupFilterType = []UsersGroupFilterType{
	UsersGroupFilterTypeGroupName,
}

func (e UsersGroupFilterType) IsValid() bool {
	switch e {
	case UsersGroupFilterTypeGroupName:
		return true
	}
	return false
}

func (e UsersGroupFilterType) String() string {
	return string(e)
}

func (e *UsersGroupFilterType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UsersGroupFilterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UsersGroupFilterType", str)
	}
	return nil
}

func (e UsersGroupFilterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
