run:
  timeout: 20m
  build-tags:
    - integration
    - nolibfb
  skip-dirs:
    - cli
    - docs
    - infra

linters-settings:
  errcheck:
    ignore: fmt:.*,Read|Write|Close|Stop|Shutdown,io:Copy
  dupl:
    threshold: 180
  funlen:
    lines: 100
    statements: 50
  goheader:
    template: |-
      Copyright (c) 2004-present Facebook All rights reserved.
      Use of this source code is governed by a BSD-style
      license that can be found in the LICENSE file.

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gocritic
    - gofmt
    - goheader
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - funlen
    - text: duplicate struct tag "choice"
      linters:
        - staticcheck
    - path: (^|/)importer($|/)
      linters:
        - funlen
    - text: "can be `fmt.Stringer`"
      linters:
        - interfacer
    - text: Profiling endpoint is automatically exposed on /debug/pprof
      linters:
        - gosec
