{{- /*
Copyright (c) 2004-present Facebook All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
*/ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "symphony.async.fullname" . }}
  labels: {{- include "symphony.async.metaLabels" . | nindent 4 }}
  {{- with .Values.async.deploymentAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.async.replicas }}
  selector:
    matchLabels: {{- include "symphony.async.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "symphony.async.selectorLabels" . | nindent 8 }}
      {{- with .Values.async.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "symphony.async.serviceAccountName" . }}
      {{- with .Values.async.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.async.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.async.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.async.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "symphony.imagePullSecrets" . | indent 6 }}
      containers:
        - name: async
          image: {{ .Values.async.image.repository }}:{{ .Values.async.image.tag }}
          imagePullPolicy: {{ .Values.async.image.pullPolicy }}
          args:
            - --web.listen-address={{ printf ":%d" (int .Values.async.service.targetPort) }}
          env:
            - name: EVENT_PUB_URL
              value: {{ required ".Values.async.spec.event.pub_url is required" .Values.async.spec.event.pub_url | quote }}
            - name: EVENT_SUB_URL
              value: {{ required ".Values.async.spec.event.sub_url is required" .Values.async.spec.event.sub_url | quote }}
            - name: EXPORT_BUCKET_URL
              value: {{ required ".Values.async.spec.export.bucket_url is required" .Values.async.spec.export.bucket_url | quote }}
            {{- with .Values.async.spec.export.bucket_prefix }}
            - name: EXPORT_BUCKET_PREFIX
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.async.spec.tenancy.tenantMaxDBConn }}
            - name: TENANCY_DB_MAX_CONN
              value: {{ . | quote }}
            {{- end }}
            - name: FEATURES_URL
              value: "http://{{ template "symphony.front.fullname" . }}:{{ .Values.front.service.internalPort }}/features"
            {{- include "symphony.loggingEnv" .Values.async | nindent 12 }}
            {{- include "symphony.tracingEnv" . | nindent 12 }}
            {{- with .Values.async.spec.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "symphony.graphDB.secretName" . }}
          ports:
            - name: http
              containerPort: {{ .Values.async.service.targetPort }}
          {{- if .Values.async.probes.liveness }}
          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: http
            {{- toYaml .Values.async.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.async.probes.readiness }}
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: http
            {{- toYaml .Values.async.probes.readiness | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.async.resources | nindent 12 }}
