{{- /*
Copyright (c) 2004-present Facebook All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
*/ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "symphony.front.fullname" . }}
  labels: {{- include "symphony.front.metaLabels" . | nindent 4 }}
spec:
  selector: {{- include "symphony.front.selectorLabels" . | nindent 4 }}
  type: {{ .Values.front.service.type }}
  ports:
    - name: http
      {{- if (and (eq .Values.front.service.type "NodePort") (not (empty .Values.front.service.nodePort))) }}
      nodePort: {{ .Values.front.service.nodePort }}
      {{- end }}
      port: {{ .Values.front.service.port }}
      targetPort: http
    - name: http-internal
      port: {{ .Values.front.service.internalPort }}
      targetPort: http-internal
    {{- include "symphony.metricsPort" . | indent 4 }}
