{
 "title": "Inventory Usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "query": "label_values(inventory_client_events_total, tenant)"
   },
   { "name": "adhoc" },
   { "name": "namespace", "query": "symphony" }
  ]
 },
 "panels": [
  {
   "title": "DAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum by (user) (increase(inventory_client_events_total{tenant=\"$tenant\", namespace=\"$namespace\"}[$__interval]) > 0))",
     "legendFormat": "users per interval"
    }
   ]
  },
  {
   "title": "User emails",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase(inventory_client_events_total{tenant=\"$tenant\", namespace=\"$namespace\"}[$__interval]) > 0)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (event) (increase(inventory_client_events_total{tenant=\"$tenant\", namespace=\"$namespace\" event=~\"add_(location_button|equipment_button|location_type_button|link)_clicked\"}[$__interval]) > 0)",
     "legendFormat": "{{event}}"
    }
   ]
  }
 ]
}