{
 "title": "Symphony / Deployment / Inventory",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "default" },
   { "name": "container", "query": "graph" },
   {
    "name": "tag",
    "query": "query_result(sum(kube_pod_container_info{namespace=\"$namespace\", container=\"$container\"}) by (image))"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployments Over Time",
   "type": "graph",
   "description": "Deployments over time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(clamp_max(sum(kube_pod_container_info{namespace=\"$namespace\", container=\"$container\"}) by (image), 1), \"tag\", \"$1\", \"image\", \".*:(.*)\")",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Currently Deployed",
   "type": "singlestat",
   "description": "Image tag currently deployed by majority",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_replace(topk(1, sum(kube_pod_container_info{namespace=\"$namespace\", container=\"$container\"}) by (image)), \"tag\", \"$1\", \"image\", \".*:(.*)\")"
    }
   ]
  },
  {
   "title": "Deployment In Progress",
   "type": "singlestat",
   "description": "Signals whether a deployment is currently in progress",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(kube_pod_container_info{namespace=\"$namespace\", container=\"$container\"}) by (image))"
    }
   ]
  }
 ]
}