// Copyright (c) 2004-present Facebook All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/facebookincubator/symphony/pkg/ent/locationtype"
	"github.com/facebookincubator/symphony/pkg/ent/resourcerelationship"
	"github.com/facebookincubator/symphony/pkg/ent/resourcetype"
)

// ResourceRelationshipCreate is the builder for creating a ResourceRelationship entity.
type ResourceRelationshipCreate struct {
	config
	mutation *ResourceRelationshipMutation
	hooks    []Hook
}

// SetCreateTime sets the create_time field.
func (rrc *ResourceRelationshipCreate) SetCreateTime(t time.Time) *ResourceRelationshipCreate {
	rrc.mutation.SetCreateTime(t)
	return rrc
}

// SetNillableCreateTime sets the create_time field if the given value is not nil.
func (rrc *ResourceRelationshipCreate) SetNillableCreateTime(t *time.Time) *ResourceRelationshipCreate {
	if t != nil {
		rrc.SetCreateTime(*t)
	}
	return rrc
}

// SetUpdateTime sets the update_time field.
func (rrc *ResourceRelationshipCreate) SetUpdateTime(t time.Time) *ResourceRelationshipCreate {
	rrc.mutation.SetUpdateTime(t)
	return rrc
}

// SetNillableUpdateTime sets the update_time field if the given value is not nil.
func (rrc *ResourceRelationshipCreate) SetNillableUpdateTime(t *time.Time) *ResourceRelationshipCreate {
	if t != nil {
		rrc.SetUpdateTime(*t)
	}
	return rrc
}

// SetName sets the name field.
func (rrc *ResourceRelationshipCreate) SetName(s string) *ResourceRelationshipCreate {
	rrc.mutation.SetName(s)
	return rrc
}

// SetResourceRelationshipType sets the ResourceRelationshipType field.
func (rrc *ResourceRelationshipCreate) SetResourceRelationshipType(rrt resourcerelationship.ResourceRelationshipType) *ResourceRelationshipCreate {
	rrc.mutation.SetResourceRelationshipType(rrt)
	return rrc
}

// SetResourceRelationshipMultiplicity sets the ResourceRelationshipMultiplicity field.
func (rrc *ResourceRelationshipCreate) SetResourceRelationshipMultiplicity(rrm resourcerelationship.ResourceRelationshipMultiplicity) *ResourceRelationshipCreate {
	rrc.mutation.SetResourceRelationshipMultiplicity(rrm)
	return rrc
}

// SetResourcetypeaID sets the resourcetypea edge to ResourceType by id.
func (rrc *ResourceRelationshipCreate) SetResourcetypeaID(id int) *ResourceRelationshipCreate {
	rrc.mutation.SetResourcetypeaID(id)
	return rrc
}

// SetNillableResourcetypeaID sets the resourcetypea edge to ResourceType by id if the given value is not nil.
func (rrc *ResourceRelationshipCreate) SetNillableResourcetypeaID(id *int) *ResourceRelationshipCreate {
	if id != nil {
		rrc = rrc.SetResourcetypeaID(*id)
	}
	return rrc
}

// SetResourcetypea sets the resourcetypea edge to ResourceType.
func (rrc *ResourceRelationshipCreate) SetResourcetypea(r *ResourceType) *ResourceRelationshipCreate {
	return rrc.SetResourcetypeaID(r.ID)
}

// SetResourcetypebID sets the resourcetypeb edge to ResourceType by id.
func (rrc *ResourceRelationshipCreate) SetResourcetypebID(id int) *ResourceRelationshipCreate {
	rrc.mutation.SetResourcetypebID(id)
	return rrc
}

// SetNillableResourcetypebID sets the resourcetypeb edge to ResourceType by id if the given value is not nil.
func (rrc *ResourceRelationshipCreate) SetNillableResourcetypebID(id *int) *ResourceRelationshipCreate {
	if id != nil {
		rrc = rrc.SetResourcetypebID(*id)
	}
	return rrc
}

// SetResourcetypeb sets the resourcetypeb edge to ResourceType.
func (rrc *ResourceRelationshipCreate) SetResourcetypeb(r *ResourceType) *ResourceRelationshipCreate {
	return rrc.SetResourcetypebID(r.ID)
}

// SetLocationTypeID sets the locationType edge to LocationType by id.
func (rrc *ResourceRelationshipCreate) SetLocationTypeID(id int) *ResourceRelationshipCreate {
	rrc.mutation.SetLocationTypeID(id)
	return rrc
}

// SetNillableLocationTypeID sets the locationType edge to LocationType by id if the given value is not nil.
func (rrc *ResourceRelationshipCreate) SetNillableLocationTypeID(id *int) *ResourceRelationshipCreate {
	if id != nil {
		rrc = rrc.SetLocationTypeID(*id)
	}
	return rrc
}

// SetLocationType sets the locationType edge to LocationType.
func (rrc *ResourceRelationshipCreate) SetLocationType(l *LocationType) *ResourceRelationshipCreate {
	return rrc.SetLocationTypeID(l.ID)
}

// Mutation returns the ResourceRelationshipMutation object of the builder.
func (rrc *ResourceRelationshipCreate) Mutation() *ResourceRelationshipMutation {
	return rrc.mutation
}

// Save creates the ResourceRelationship in the database.
func (rrc *ResourceRelationshipCreate) Save(ctx context.Context) (*ResourceRelationship, error) {
	var (
		err  error
		node *ResourceRelationship
	)
	rrc.defaults()
	if len(rrc.hooks) == 0 {
		if err = rrc.check(); err != nil {
			return nil, err
		}
		node, err = rrc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResourceRelationshipMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rrc.check(); err != nil {
				return nil, err
			}
			rrc.mutation = mutation
			node, err = rrc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rrc.hooks) - 1; i >= 0; i-- {
			mut = rrc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rrc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rrc *ResourceRelationshipCreate) SaveX(ctx context.Context) *ResourceRelationship {
	v, err := rrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (rrc *ResourceRelationshipCreate) defaults() {
	if _, ok := rrc.mutation.CreateTime(); !ok {
		v := resourcerelationship.DefaultCreateTime()
		rrc.mutation.SetCreateTime(v)
	}
	if _, ok := rrc.mutation.UpdateTime(); !ok {
		v := resourcerelationship.DefaultUpdateTime()
		rrc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rrc *ResourceRelationshipCreate) check() error {
	if _, ok := rrc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New("ent: missing required field \"create_time\"")}
	}
	if _, ok := rrc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New("ent: missing required field \"update_time\"")}
	}
	if _, ok := rrc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := rrc.mutation.Name(); ok {
		if err := resourcerelationship.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if _, ok := rrc.mutation.ResourceRelationshipType(); !ok {
		return &ValidationError{Name: "ResourceRelationshipType", err: errors.New("ent: missing required field \"ResourceRelationshipType\"")}
	}
	if v, ok := rrc.mutation.ResourceRelationshipType(); ok {
		if err := resourcerelationship.ResourceRelationshipTypeValidator(v); err != nil {
			return &ValidationError{Name: "ResourceRelationshipType", err: fmt.Errorf("ent: validator failed for field \"ResourceRelationshipType\": %w", err)}
		}
	}
	if _, ok := rrc.mutation.ResourceRelationshipMultiplicity(); !ok {
		return &ValidationError{Name: "ResourceRelationshipMultiplicity", err: errors.New("ent: missing required field \"ResourceRelationshipMultiplicity\"")}
	}
	if v, ok := rrc.mutation.ResourceRelationshipMultiplicity(); ok {
		if err := resourcerelationship.ResourceRelationshipMultiplicityValidator(v); err != nil {
			return &ValidationError{Name: "ResourceRelationshipMultiplicity", err: fmt.Errorf("ent: validator failed for field \"ResourceRelationshipMultiplicity\": %w", err)}
		}
	}
	return nil
}

func (rrc *ResourceRelationshipCreate) sqlSave(ctx context.Context) (*ResourceRelationship, error) {
	_node, _spec := rrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rrc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rrc *ResourceRelationshipCreate) createSpec() (*ResourceRelationship, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceRelationship{config: rrc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: resourcerelationship.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resourcerelationship.FieldID,
			},
		}
	)
	if value, ok := rrc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resourcerelationship.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := rrc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resourcerelationship.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := rrc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcerelationship.FieldName,
		})
		_node.Name = value
	}
	if value, ok := rrc.mutation.ResourceRelationshipType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: resourcerelationship.FieldResourceRelationshipType,
		})
		_node.ResourceRelationshipType = value
	}
	if value, ok := rrc.mutation.ResourceRelationshipMultiplicity(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: resourcerelationship.FieldResourceRelationshipMultiplicity,
		})
		_node.ResourceRelationshipMultiplicity = value
	}
	if nodes := rrc.mutation.ResourcetypeaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcerelationship.ResourcetypeaTable,
			Columns: []string{resourcerelationship.ResourcetypeaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rrc.mutation.ResourcetypebIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcerelationship.ResourcetypebTable,
			Columns: []string{resourcerelationship.ResourcetypebColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rrc.mutation.LocationTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcerelationship.LocationTypeTable,
			Columns: []string{resourcerelationship.LocationTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: locationtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResourceRelationshipCreateBulk is the builder for creating a bulk of ResourceRelationship entities.
type ResourceRelationshipCreateBulk struct {
	config
	builders []*ResourceRelationshipCreate
}

// Save creates the ResourceRelationship entities in the database.
func (rrcb *ResourceRelationshipCreateBulk) Save(ctx context.Context) ([]*ResourceRelationship, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rrcb.builders))
	nodes := make([]*ResourceRelationship, len(rrcb.builders))
	mutators := make([]Mutator, len(rrcb.builders))
	for i := range rrcb.builders {
		func(i int, root context.Context) {
			builder := rrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceRelationshipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rrcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rrcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (rrcb *ResourceRelationshipCreateBulk) SaveX(ctx context.Context) []*ResourceRelationship {
	v, err := rrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
