// Copyright (c) 2004-present Facebook All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/facebookincubator/symphony/pkg/ent/predicate"
	"github.com/facebookincubator/symphony/pkg/ent/resourcerelationship"
	"github.com/facebookincubator/symphony/pkg/ent/resourcetype"
	"github.com/facebookincubator/symphony/pkg/ent/resourcetypebasetype"
	"github.com/facebookincubator/symphony/pkg/ent/resourcetypeclass"
)

// ResourceTypeUpdate is the builder for updating ResourceType entities.
type ResourceTypeUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceTypeMutation
}

// Where adds a new predicate for the builder.
func (rtu *ResourceTypeUpdate) Where(ps ...predicate.ResourceType) *ResourceTypeUpdate {
	rtu.mutation.predicates = append(rtu.mutation.predicates, ps...)
	return rtu
}

// SetName sets the name field.
func (rtu *ResourceTypeUpdate) SetName(s string) *ResourceTypeUpdate {
	rtu.mutation.SetName(s)
	return rtu
}

// SetResourcetypeclassID sets the resourcetypeclass edge to ResourceTypeClass by id.
func (rtu *ResourceTypeUpdate) SetResourcetypeclassID(id int) *ResourceTypeUpdate {
	rtu.mutation.SetResourcetypeclassID(id)
	return rtu
}

// SetNillableResourcetypeclassID sets the resourcetypeclass edge to ResourceTypeClass by id if the given value is not nil.
func (rtu *ResourceTypeUpdate) SetNillableResourcetypeclassID(id *int) *ResourceTypeUpdate {
	if id != nil {
		rtu = rtu.SetResourcetypeclassID(*id)
	}
	return rtu
}

// SetResourcetypeclass sets the resourcetypeclass edge to ResourceTypeClass.
func (rtu *ResourceTypeUpdate) SetResourcetypeclass(r *ResourceTypeClass) *ResourceTypeUpdate {
	return rtu.SetResourcetypeclassID(r.ID)
}

// SetResourcetypebasetypeID sets the resourcetypebasetype edge to ResourceTypeBaseType by id.
func (rtu *ResourceTypeUpdate) SetResourcetypebasetypeID(id int) *ResourceTypeUpdate {
	rtu.mutation.SetResourcetypebasetypeID(id)
	return rtu
}

// SetNillableResourcetypebasetypeID sets the resourcetypebasetype edge to ResourceTypeBaseType by id if the given value is not nil.
func (rtu *ResourceTypeUpdate) SetNillableResourcetypebasetypeID(id *int) *ResourceTypeUpdate {
	if id != nil {
		rtu = rtu.SetResourcetypebasetypeID(*id)
	}
	return rtu
}

// SetResourcetypebasetype sets the resourcetypebasetype edge to ResourceTypeBaseType.
func (rtu *ResourceTypeUpdate) SetResourcetypebasetype(r *ResourceTypeBaseType) *ResourceTypeUpdate {
	return rtu.SetResourcetypebasetypeID(r.ID)
}

// AddResourceRelationshipFkAIDs adds the resource_relationship_fk_a edge to ResourceRelationship by ids.
func (rtu *ResourceTypeUpdate) AddResourceRelationshipFkAIDs(ids ...int) *ResourceTypeUpdate {
	rtu.mutation.AddResourceRelationshipFkAIDs(ids...)
	return rtu
}

// AddResourceRelationshipFkA adds the resource_relationship_fk_a edges to ResourceRelationship.
func (rtu *ResourceTypeUpdate) AddResourceRelationshipFkA(r ...*ResourceRelationship) *ResourceTypeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtu.AddResourceRelationshipFkAIDs(ids...)
}

// AddResourceRelationshipFkBIDs adds the resource_relationship_fk_b edge to ResourceRelationship by ids.
func (rtu *ResourceTypeUpdate) AddResourceRelationshipFkBIDs(ids ...int) *ResourceTypeUpdate {
	rtu.mutation.AddResourceRelationshipFkBIDs(ids...)
	return rtu
}

// AddResourceRelationshipFkB adds the resource_relationship_fk_b edges to ResourceRelationship.
func (rtu *ResourceTypeUpdate) AddResourceRelationshipFkB(r ...*ResourceRelationship) *ResourceTypeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtu.AddResourceRelationshipFkBIDs(ids...)
}

// Mutation returns the ResourceTypeMutation object of the builder.
func (rtu *ResourceTypeUpdate) Mutation() *ResourceTypeMutation {
	return rtu.mutation
}

// ClearResourcetypeclass clears the "resourcetypeclass" edge to type ResourceTypeClass.
func (rtu *ResourceTypeUpdate) ClearResourcetypeclass() *ResourceTypeUpdate {
	rtu.mutation.ClearResourcetypeclass()
	return rtu
}

// ClearResourcetypebasetype clears the "resourcetypebasetype" edge to type ResourceTypeBaseType.
func (rtu *ResourceTypeUpdate) ClearResourcetypebasetype() *ResourceTypeUpdate {
	rtu.mutation.ClearResourcetypebasetype()
	return rtu
}

// ClearResourceRelationshipFkA clears all "resource_relationship_fk_a" edges to type ResourceRelationship.
func (rtu *ResourceTypeUpdate) ClearResourceRelationshipFkA() *ResourceTypeUpdate {
	rtu.mutation.ClearResourceRelationshipFkA()
	return rtu
}

// RemoveResourceRelationshipFkAIDs removes the resource_relationship_fk_a edge to ResourceRelationship by ids.
func (rtu *ResourceTypeUpdate) RemoveResourceRelationshipFkAIDs(ids ...int) *ResourceTypeUpdate {
	rtu.mutation.RemoveResourceRelationshipFkAIDs(ids...)
	return rtu
}

// RemoveResourceRelationshipFkA removes resource_relationship_fk_a edges to ResourceRelationship.
func (rtu *ResourceTypeUpdate) RemoveResourceRelationshipFkA(r ...*ResourceRelationship) *ResourceTypeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtu.RemoveResourceRelationshipFkAIDs(ids...)
}

// ClearResourceRelationshipFkB clears all "resource_relationship_fk_b" edges to type ResourceRelationship.
func (rtu *ResourceTypeUpdate) ClearResourceRelationshipFkB() *ResourceTypeUpdate {
	rtu.mutation.ClearResourceRelationshipFkB()
	return rtu
}

// RemoveResourceRelationshipFkBIDs removes the resource_relationship_fk_b edge to ResourceRelationship by ids.
func (rtu *ResourceTypeUpdate) RemoveResourceRelationshipFkBIDs(ids ...int) *ResourceTypeUpdate {
	rtu.mutation.RemoveResourceRelationshipFkBIDs(ids...)
	return rtu
}

// RemoveResourceRelationshipFkB removes resource_relationship_fk_b edges to ResourceRelationship.
func (rtu *ResourceTypeUpdate) RemoveResourceRelationshipFkB(r ...*ResourceRelationship) *ResourceTypeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtu.RemoveResourceRelationshipFkBIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rtu *ResourceTypeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	rtu.defaults()
	if len(rtu.hooks) == 0 {
		if err = rtu.check(); err != nil {
			return 0, err
		}
		affected, err = rtu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResourceTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rtu.check(); err != nil {
				return 0, err
			}
			rtu.mutation = mutation
			affected, err = rtu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rtu.hooks) - 1; i >= 0; i-- {
			mut = rtu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rtu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (rtu *ResourceTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := rtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rtu *ResourceTypeUpdate) Exec(ctx context.Context) error {
	_, err := rtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtu *ResourceTypeUpdate) ExecX(ctx context.Context) {
	if err := rtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rtu *ResourceTypeUpdate) defaults() {
	if _, ok := rtu.mutation.UpdateTime(); !ok {
		v := resourcetype.UpdateDefaultUpdateTime()
		rtu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtu *ResourceTypeUpdate) check() error {
	if v, ok := rtu.mutation.Name(); ok {
		if err := resourcetype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	return nil
}

func (rtu *ResourceTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   resourcetype.Table,
			Columns: resourcetype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resourcetype.FieldID,
			},
		},
	}
	if ps := rtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resourcetype.FieldUpdateTime,
		})
	}
	if value, ok := rtu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcetype.FieldName,
		})
	}
	if rtu.mutation.ResourcetypeclassCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcetype.ResourcetypeclassTable,
			Columns: []string{resourcetype.ResourcetypeclassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetypeclass.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtu.mutation.ResourcetypeclassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcetype.ResourcetypeclassTable,
			Columns: []string{resourcetype.ResourcetypeclassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetypeclass.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rtu.mutation.ResourcetypebasetypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcetype.ResourcetypebasetypeTable,
			Columns: []string{resourcetype.ResourcetypebasetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetypebasetype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtu.mutation.ResourcetypebasetypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcetype.ResourcetypebasetypeTable,
			Columns: []string{resourcetype.ResourcetypebasetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetypebasetype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rtu.mutation.ResourceRelationshipFkACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkATable,
			Columns: []string{resourcetype.ResourceRelationshipFkAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtu.mutation.RemovedResourceRelationshipFkAIDs(); len(nodes) > 0 && !rtu.mutation.ResourceRelationshipFkACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkATable,
			Columns: []string{resourcetype.ResourceRelationshipFkAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtu.mutation.ResourceRelationshipFkAIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkATable,
			Columns: []string{resourcetype.ResourceRelationshipFkAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rtu.mutation.ResourceRelationshipFkBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkBTable,
			Columns: []string{resourcetype.ResourceRelationshipFkBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtu.mutation.RemovedResourceRelationshipFkBIDs(); len(nodes) > 0 && !rtu.mutation.ResourceRelationshipFkBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkBTable,
			Columns: []string{resourcetype.ResourceRelationshipFkBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtu.mutation.ResourceRelationshipFkBIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkBTable,
			Columns: []string{resourcetype.ResourceRelationshipFkBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcetype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ResourceTypeUpdateOne is the builder for updating a single ResourceType entity.
type ResourceTypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *ResourceTypeMutation
}

// SetName sets the name field.
func (rtuo *ResourceTypeUpdateOne) SetName(s string) *ResourceTypeUpdateOne {
	rtuo.mutation.SetName(s)
	return rtuo
}

// SetResourcetypeclassID sets the resourcetypeclass edge to ResourceTypeClass by id.
func (rtuo *ResourceTypeUpdateOne) SetResourcetypeclassID(id int) *ResourceTypeUpdateOne {
	rtuo.mutation.SetResourcetypeclassID(id)
	return rtuo
}

// SetNillableResourcetypeclassID sets the resourcetypeclass edge to ResourceTypeClass by id if the given value is not nil.
func (rtuo *ResourceTypeUpdateOne) SetNillableResourcetypeclassID(id *int) *ResourceTypeUpdateOne {
	if id != nil {
		rtuo = rtuo.SetResourcetypeclassID(*id)
	}
	return rtuo
}

// SetResourcetypeclass sets the resourcetypeclass edge to ResourceTypeClass.
func (rtuo *ResourceTypeUpdateOne) SetResourcetypeclass(r *ResourceTypeClass) *ResourceTypeUpdateOne {
	return rtuo.SetResourcetypeclassID(r.ID)
}

// SetResourcetypebasetypeID sets the resourcetypebasetype edge to ResourceTypeBaseType by id.
func (rtuo *ResourceTypeUpdateOne) SetResourcetypebasetypeID(id int) *ResourceTypeUpdateOne {
	rtuo.mutation.SetResourcetypebasetypeID(id)
	return rtuo
}

// SetNillableResourcetypebasetypeID sets the resourcetypebasetype edge to ResourceTypeBaseType by id if the given value is not nil.
func (rtuo *ResourceTypeUpdateOne) SetNillableResourcetypebasetypeID(id *int) *ResourceTypeUpdateOne {
	if id != nil {
		rtuo = rtuo.SetResourcetypebasetypeID(*id)
	}
	return rtuo
}

// SetResourcetypebasetype sets the resourcetypebasetype edge to ResourceTypeBaseType.
func (rtuo *ResourceTypeUpdateOne) SetResourcetypebasetype(r *ResourceTypeBaseType) *ResourceTypeUpdateOne {
	return rtuo.SetResourcetypebasetypeID(r.ID)
}

// AddResourceRelationshipFkAIDs adds the resource_relationship_fk_a edge to ResourceRelationship by ids.
func (rtuo *ResourceTypeUpdateOne) AddResourceRelationshipFkAIDs(ids ...int) *ResourceTypeUpdateOne {
	rtuo.mutation.AddResourceRelationshipFkAIDs(ids...)
	return rtuo
}

// AddResourceRelationshipFkA adds the resource_relationship_fk_a edges to ResourceRelationship.
func (rtuo *ResourceTypeUpdateOne) AddResourceRelationshipFkA(r ...*ResourceRelationship) *ResourceTypeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtuo.AddResourceRelationshipFkAIDs(ids...)
}

// AddResourceRelationshipFkBIDs adds the resource_relationship_fk_b edge to ResourceRelationship by ids.
func (rtuo *ResourceTypeUpdateOne) AddResourceRelationshipFkBIDs(ids ...int) *ResourceTypeUpdateOne {
	rtuo.mutation.AddResourceRelationshipFkBIDs(ids...)
	return rtuo
}

// AddResourceRelationshipFkB adds the resource_relationship_fk_b edges to ResourceRelationship.
func (rtuo *ResourceTypeUpdateOne) AddResourceRelationshipFkB(r ...*ResourceRelationship) *ResourceTypeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtuo.AddResourceRelationshipFkBIDs(ids...)
}

// Mutation returns the ResourceTypeMutation object of the builder.
func (rtuo *ResourceTypeUpdateOne) Mutation() *ResourceTypeMutation {
	return rtuo.mutation
}

// ClearResourcetypeclass clears the "resourcetypeclass" edge to type ResourceTypeClass.
func (rtuo *ResourceTypeUpdateOne) ClearResourcetypeclass() *ResourceTypeUpdateOne {
	rtuo.mutation.ClearResourcetypeclass()
	return rtuo
}

// ClearResourcetypebasetype clears the "resourcetypebasetype" edge to type ResourceTypeBaseType.
func (rtuo *ResourceTypeUpdateOne) ClearResourcetypebasetype() *ResourceTypeUpdateOne {
	rtuo.mutation.ClearResourcetypebasetype()
	return rtuo
}

// ClearResourceRelationshipFkA clears all "resource_relationship_fk_a" edges to type ResourceRelationship.
func (rtuo *ResourceTypeUpdateOne) ClearResourceRelationshipFkA() *ResourceTypeUpdateOne {
	rtuo.mutation.ClearResourceRelationshipFkA()
	return rtuo
}

// RemoveResourceRelationshipFkAIDs removes the resource_relationship_fk_a edge to ResourceRelationship by ids.
func (rtuo *ResourceTypeUpdateOne) RemoveResourceRelationshipFkAIDs(ids ...int) *ResourceTypeUpdateOne {
	rtuo.mutation.RemoveResourceRelationshipFkAIDs(ids...)
	return rtuo
}

// RemoveResourceRelationshipFkA removes resource_relationship_fk_a edges to ResourceRelationship.
func (rtuo *ResourceTypeUpdateOne) RemoveResourceRelationshipFkA(r ...*ResourceRelationship) *ResourceTypeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtuo.RemoveResourceRelationshipFkAIDs(ids...)
}

// ClearResourceRelationshipFkB clears all "resource_relationship_fk_b" edges to type ResourceRelationship.
func (rtuo *ResourceTypeUpdateOne) ClearResourceRelationshipFkB() *ResourceTypeUpdateOne {
	rtuo.mutation.ClearResourceRelationshipFkB()
	return rtuo
}

// RemoveResourceRelationshipFkBIDs removes the resource_relationship_fk_b edge to ResourceRelationship by ids.
func (rtuo *ResourceTypeUpdateOne) RemoveResourceRelationshipFkBIDs(ids ...int) *ResourceTypeUpdateOne {
	rtuo.mutation.RemoveResourceRelationshipFkBIDs(ids...)
	return rtuo
}

// RemoveResourceRelationshipFkB removes resource_relationship_fk_b edges to ResourceRelationship.
func (rtuo *ResourceTypeUpdateOne) RemoveResourceRelationshipFkB(r ...*ResourceRelationship) *ResourceTypeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtuo.RemoveResourceRelationshipFkBIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (rtuo *ResourceTypeUpdateOne) Save(ctx context.Context) (*ResourceType, error) {
	var (
		err  error
		node *ResourceType
	)
	rtuo.defaults()
	if len(rtuo.hooks) == 0 {
		if err = rtuo.check(); err != nil {
			return nil, err
		}
		node, err = rtuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResourceTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rtuo.check(); err != nil {
				return nil, err
			}
			rtuo.mutation = mutation
			node, err = rtuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rtuo.hooks) - 1; i >= 0; i-- {
			mut = rtuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rtuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (rtuo *ResourceTypeUpdateOne) SaveX(ctx context.Context) *ResourceType {
	node, err := rtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rtuo *ResourceTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := rtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtuo *ResourceTypeUpdateOne) ExecX(ctx context.Context) {
	if err := rtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rtuo *ResourceTypeUpdateOne) defaults() {
	if _, ok := rtuo.mutation.UpdateTime(); !ok {
		v := resourcetype.UpdateDefaultUpdateTime()
		rtuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtuo *ResourceTypeUpdateOne) check() error {
	if v, ok := rtuo.mutation.Name(); ok {
		if err := resourcetype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	return nil
}

func (rtuo *ResourceTypeUpdateOne) sqlSave(ctx context.Context) (_node *ResourceType, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   resourcetype.Table,
			Columns: resourcetype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resourcetype.FieldID,
			},
		},
	}
	id, ok := rtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ResourceType.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := rtuo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resourcetype.FieldUpdateTime,
		})
	}
	if value, ok := rtuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resourcetype.FieldName,
		})
	}
	if rtuo.mutation.ResourcetypeclassCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcetype.ResourcetypeclassTable,
			Columns: []string{resourcetype.ResourcetypeclassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetypeclass.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtuo.mutation.ResourcetypeclassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcetype.ResourcetypeclassTable,
			Columns: []string{resourcetype.ResourcetypeclassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetypeclass.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rtuo.mutation.ResourcetypebasetypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcetype.ResourcetypebasetypeTable,
			Columns: []string{resourcetype.ResourcetypebasetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetypebasetype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtuo.mutation.ResourcetypebasetypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resourcetype.ResourcetypebasetypeTable,
			Columns: []string{resourcetype.ResourcetypebasetypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcetypebasetype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rtuo.mutation.ResourceRelationshipFkACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkATable,
			Columns: []string{resourcetype.ResourceRelationshipFkAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtuo.mutation.RemovedResourceRelationshipFkAIDs(); len(nodes) > 0 && !rtuo.mutation.ResourceRelationshipFkACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkATable,
			Columns: []string{resourcetype.ResourceRelationshipFkAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtuo.mutation.ResourceRelationshipFkAIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkATable,
			Columns: []string{resourcetype.ResourceRelationshipFkAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if rtuo.mutation.ResourceRelationshipFkBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkBTable,
			Columns: []string{resourcetype.ResourceRelationshipFkBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtuo.mutation.RemovedResourceRelationshipFkBIDs(); len(nodes) > 0 && !rtuo.mutation.ResourceRelationshipFkBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkBTable,
			Columns: []string{resourcetype.ResourceRelationshipFkBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rtuo.mutation.ResourceRelationshipFkBIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resourcetype.ResourceRelationshipFkBTable,
			Columns: []string{resourcetype.ResourceRelationshipFkBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resourcerelationship.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ResourceType{config: rtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, rtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourcetype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
