// Copyright (c) 2004-present Facebook All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/facebookincubator/symphony/pkg/ent/permissionspolicy"
	"github.com/facebookincubator/symphony/pkg/ent/predicate"
	"github.com/facebookincubator/symphony/pkg/ent/resourcetype"
	"github.com/facebookincubator/symphony/pkg/ent/resourcetypeclass"
)

// ResourceTypeClassQuery is the builder for querying ResourceTypeClass entities.
type ResourceTypeClassQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.ResourceTypeClass
	// eager-loading edges.
	withResourceTypeFk *ResourceTypeQuery
	withPolicies       *PermissionsPolicyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (rtcq *ResourceTypeClassQuery) Where(ps ...predicate.ResourceTypeClass) *ResourceTypeClassQuery {
	rtcq.predicates = append(rtcq.predicates, ps...)
	return rtcq
}

// Limit adds a limit step to the query.
func (rtcq *ResourceTypeClassQuery) Limit(limit int) *ResourceTypeClassQuery {
	rtcq.limit = &limit
	return rtcq
}

// Offset adds an offset step to the query.
func (rtcq *ResourceTypeClassQuery) Offset(offset int) *ResourceTypeClassQuery {
	rtcq.offset = &offset
	return rtcq
}

// Order adds an order step to the query.
func (rtcq *ResourceTypeClassQuery) Order(o ...OrderFunc) *ResourceTypeClassQuery {
	rtcq.order = append(rtcq.order, o...)
	return rtcq
}

// QueryResourceTypeFk chains the current query on the resource_type_fk edge.
func (rtcq *ResourceTypeClassQuery) QueryResourceTypeFk() *ResourceTypeQuery {
	query := &ResourceTypeQuery{config: rtcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rtcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rtcq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourcetypeclass.Table, resourcetypeclass.FieldID, selector),
			sqlgraph.To(resourcetype.Table, resourcetype.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, resourcetypeclass.ResourceTypeFkTable, resourcetypeclass.ResourceTypeFkColumn),
		)
		fromU = sqlgraph.SetNeighbors(rtcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPolicies chains the current query on the policies edge.
func (rtcq *ResourceTypeClassQuery) QueryPolicies() *PermissionsPolicyQuery {
	query := &PermissionsPolicyQuery{config: rtcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rtcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rtcq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourcetypeclass.Table, resourcetypeclass.FieldID, selector),
			sqlgraph.To(permissionspolicy.Table, permissionspolicy.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, resourcetypeclass.PoliciesTable, resourcetypeclass.PoliciesColumn),
		)
		fromU = sqlgraph.SetNeighbors(rtcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ResourceTypeClass entity in the query. Returns *NotFoundError when no resourcetypeclass was found.
func (rtcq *ResourceTypeClassQuery) First(ctx context.Context) (*ResourceTypeClass, error) {
	nodes, err := rtcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{resourcetypeclass.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rtcq *ResourceTypeClassQuery) FirstX(ctx context.Context) *ResourceTypeClass {
	node, err := rtcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ResourceTypeClass id in the query. Returns *NotFoundError when no id was found.
func (rtcq *ResourceTypeClassQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rtcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{resourcetypeclass.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rtcq *ResourceTypeClassQuery) FirstIDX(ctx context.Context) int {
	id, err := rtcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only ResourceTypeClass entity in the query, returns an error if not exactly one entity was returned.
func (rtcq *ResourceTypeClassQuery) Only(ctx context.Context) (*ResourceTypeClass, error) {
	nodes, err := rtcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{resourcetypeclass.Label}
	default:
		return nil, &NotSingularError{resourcetypeclass.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rtcq *ResourceTypeClassQuery) OnlyX(ctx context.Context) *ResourceTypeClass {
	node, err := rtcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only ResourceTypeClass id in the query, returns an error if not exactly one id was returned.
func (rtcq *ResourceTypeClassQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rtcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = &NotSingularError{resourcetypeclass.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rtcq *ResourceTypeClassQuery) OnlyIDX(ctx context.Context) int {
	id, err := rtcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ResourceTypeClasses.
func (rtcq *ResourceTypeClassQuery) All(ctx context.Context) ([]*ResourceTypeClass, error) {
	if err := rtcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rtcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rtcq *ResourceTypeClassQuery) AllX(ctx context.Context) []*ResourceTypeClass {
	nodes, err := rtcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ResourceTypeClass ids.
func (rtcq *ResourceTypeClassQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := rtcq.Select(resourcetypeclass.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rtcq *ResourceTypeClassQuery) IDsX(ctx context.Context) []int {
	ids, err := rtcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rtcq *ResourceTypeClassQuery) Count(ctx context.Context) (int, error) {
	if err := rtcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rtcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rtcq *ResourceTypeClassQuery) CountX(ctx context.Context) int {
	count, err := rtcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rtcq *ResourceTypeClassQuery) Exist(ctx context.Context) (bool, error) {
	if err := rtcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rtcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rtcq *ResourceTypeClassQuery) ExistX(ctx context.Context) bool {
	exist, err := rtcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rtcq *ResourceTypeClassQuery) Clone() *ResourceTypeClassQuery {
	if rtcq == nil {
		return nil
	}
	return &ResourceTypeClassQuery{
		config:             rtcq.config,
		limit:              rtcq.limit,
		offset:             rtcq.offset,
		order:              append([]OrderFunc{}, rtcq.order...),
		unique:             append([]string{}, rtcq.unique...),
		predicates:         append([]predicate.ResourceTypeClass{}, rtcq.predicates...),
		withResourceTypeFk: rtcq.withResourceTypeFk.Clone(),
		withPolicies:       rtcq.withPolicies.Clone(),
		// clone intermediate query.
		sql:  rtcq.sql.Clone(),
		path: rtcq.path,
	}
}

//  WithResourceTypeFk tells the query-builder to eager-loads the nodes that are connected to
// the "resource_type_fk" edge. The optional arguments used to configure the query builder of the edge.
func (rtcq *ResourceTypeClassQuery) WithResourceTypeFk(opts ...func(*ResourceTypeQuery)) *ResourceTypeClassQuery {
	query := &ResourceTypeQuery{config: rtcq.config}
	for _, opt := range opts {
		opt(query)
	}
	rtcq.withResourceTypeFk = query
	return rtcq
}

//  WithPolicies tells the query-builder to eager-loads the nodes that are connected to
// the "policies" edge. The optional arguments used to configure the query builder of the edge.
func (rtcq *ResourceTypeClassQuery) WithPolicies(opts ...func(*PermissionsPolicyQuery)) *ResourceTypeClassQuery {
	query := &PermissionsPolicyQuery{config: rtcq.config}
	for _, opt := range opts {
		opt(query)
	}
	rtcq.withPolicies = query
	return rtcq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ResourceTypeClass.Query().
//		GroupBy(resourcetypeclass.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rtcq *ResourceTypeClassQuery) GroupBy(field string, fields ...string) *ResourceTypeClassGroupBy {
	group := &ResourceTypeClassGroupBy{config: rtcq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rtcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rtcq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.ResourceTypeClass.Query().
//		Select(resourcetypeclass.FieldCreateTime).
//		Scan(ctx, &v)
//
func (rtcq *ResourceTypeClassQuery) Select(field string, fields ...string) *ResourceTypeClassSelect {
	selector := &ResourceTypeClassSelect{config: rtcq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rtcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rtcq.sqlQuery(), nil
	}
	return selector
}

func (rtcq *ResourceTypeClassQuery) prepareQuery(ctx context.Context) error {
	if rtcq.path != nil {
		prev, err := rtcq.path(ctx)
		if err != nil {
			return err
		}
		rtcq.sql = prev
	}
	if err := resourcetypeclass.Policy.EvalQuery(ctx, rtcq); err != nil {
		return err
	}
	return nil
}

func (rtcq *ResourceTypeClassQuery) sqlAll(ctx context.Context) ([]*ResourceTypeClass, error) {
	var (
		nodes       = []*ResourceTypeClass{}
		_spec       = rtcq.querySpec()
		loadedTypes = [2]bool{
			rtcq.withResourceTypeFk != nil,
			rtcq.withPolicies != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &ResourceTypeClass{config: rtcq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, rtcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := rtcq.withResourceTypeFk; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*ResourceTypeClass)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.ResourceTypeFk = []*ResourceType{}
		}
		query.withFKs = true
		query.Where(predicate.ResourceType(func(s *sql.Selector) {
			s.Where(sql.InValues(resourcetypeclass.ResourceTypeFkColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.resource_type_class_resource_type_fk
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "resource_type_class_resource_type_fk" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "resource_type_class_resource_type_fk" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.ResourceTypeFk = append(node.Edges.ResourceTypeFk, n)
		}
	}

	if query := rtcq.withPolicies; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*ResourceTypeClass)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Policies = []*PermissionsPolicy{}
		}
		query.withFKs = true
		query.Where(predicate.PermissionsPolicy(func(s *sql.Selector) {
			s.Where(sql.InValues(resourcetypeclass.PoliciesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.resource_type_class_policies
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "resource_type_class_policies" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "resource_type_class_policies" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Policies = append(node.Edges.Policies, n)
		}
	}

	return nodes, nil
}

func (rtcq *ResourceTypeClassQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rtcq.querySpec()
	return sqlgraph.CountNodes(ctx, rtcq.driver, _spec)
}

func (rtcq *ResourceTypeClassQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rtcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (rtcq *ResourceTypeClassQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   resourcetypeclass.Table,
			Columns: resourcetypeclass.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: resourcetypeclass.FieldID,
			},
		},
		From:   rtcq.sql,
		Unique: true,
	}
	if ps := rtcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rtcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rtcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rtcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, resourcetypeclass.ValidColumn)
			}
		}
	}
	return _spec
}

func (rtcq *ResourceTypeClassQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(rtcq.driver.Dialect())
	t1 := builder.Table(resourcetypeclass.Table)
	selector := builder.Select(t1.Columns(resourcetypeclass.Columns...)...).From(t1)
	if rtcq.sql != nil {
		selector = rtcq.sql
		selector.Select(selector.Columns(resourcetypeclass.Columns...)...)
	}
	for _, p := range rtcq.predicates {
		p(selector)
	}
	for _, p := range rtcq.order {
		p(selector, resourcetypeclass.ValidColumn)
	}
	if offset := rtcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rtcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ResourceTypeClassGroupBy is the builder for group-by ResourceTypeClass entities.
type ResourceTypeClassGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rtcgb *ResourceTypeClassGroupBy) Aggregate(fns ...AggregateFunc) *ResourceTypeClassGroupBy {
	rtcgb.fns = append(rtcgb.fns, fns...)
	return rtcgb
}

// Scan applies the group-by query and scan the result into the given value.
func (rtcgb *ResourceTypeClassGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rtcgb.path(ctx)
	if err != nil {
		return err
	}
	rtcgb.sql = query
	return rtcgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rtcgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (rtcgb *ResourceTypeClassGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rtcgb.fields) > 1 {
		return nil, errors.New("ent: ResourceTypeClassGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rtcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) StringsX(ctx context.Context) []string {
	v, err := rtcgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (rtcgb *ResourceTypeClassGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rtcgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = fmt.Errorf("ent: ResourceTypeClassGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) StringX(ctx context.Context) string {
	v, err := rtcgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (rtcgb *ResourceTypeClassGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rtcgb.fields) > 1 {
		return nil, errors.New("ent: ResourceTypeClassGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rtcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) IntsX(ctx context.Context) []int {
	v, err := rtcgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (rtcgb *ResourceTypeClassGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rtcgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = fmt.Errorf("ent: ResourceTypeClassGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) IntX(ctx context.Context) int {
	v, err := rtcgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (rtcgb *ResourceTypeClassGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rtcgb.fields) > 1 {
		return nil, errors.New("ent: ResourceTypeClassGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rtcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rtcgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (rtcgb *ResourceTypeClassGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rtcgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = fmt.Errorf("ent: ResourceTypeClassGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) Float64X(ctx context.Context) float64 {
	v, err := rtcgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (rtcgb *ResourceTypeClassGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rtcgb.fields) > 1 {
		return nil, errors.New("ent: ResourceTypeClassGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rtcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rtcgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (rtcgb *ResourceTypeClassGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rtcgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = fmt.Errorf("ent: ResourceTypeClassGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rtcgb *ResourceTypeClassGroupBy) BoolX(ctx context.Context) bool {
	v, err := rtcgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rtcgb *ResourceTypeClassGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rtcgb.fields {
		if !resourcetypeclass.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rtcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rtcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rtcgb *ResourceTypeClassGroupBy) sqlQuery() *sql.Selector {
	selector := rtcgb.sql
	columns := make([]string, 0, len(rtcgb.fields)+len(rtcgb.fns))
	columns = append(columns, rtcgb.fields...)
	for _, fn := range rtcgb.fns {
		columns = append(columns, fn(selector, resourcetypeclass.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(rtcgb.fields...)
}

// ResourceTypeClassSelect is the builder for select fields of ResourceTypeClass entities.
type ResourceTypeClassSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (rtcs *ResourceTypeClassSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := rtcs.path(ctx)
	if err != nil {
		return err
	}
	rtcs.sql = query
	return rtcs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) ScanX(ctx context.Context, v interface{}) {
	if err := rtcs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (rtcs *ResourceTypeClassSelect) Strings(ctx context.Context) ([]string, error) {
	if len(rtcs.fields) > 1 {
		return nil, errors.New("ent: ResourceTypeClassSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := rtcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) StringsX(ctx context.Context) []string {
	v, err := rtcs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (rtcs *ResourceTypeClassSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rtcs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = fmt.Errorf("ent: ResourceTypeClassSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) StringX(ctx context.Context) string {
	v, err := rtcs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (rtcs *ResourceTypeClassSelect) Ints(ctx context.Context) ([]int, error) {
	if len(rtcs.fields) > 1 {
		return nil, errors.New("ent: ResourceTypeClassSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := rtcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) IntsX(ctx context.Context) []int {
	v, err := rtcs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (rtcs *ResourceTypeClassSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rtcs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = fmt.Errorf("ent: ResourceTypeClassSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) IntX(ctx context.Context) int {
	v, err := rtcs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (rtcs *ResourceTypeClassSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(rtcs.fields) > 1 {
		return nil, errors.New("ent: ResourceTypeClassSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := rtcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) Float64sX(ctx context.Context) []float64 {
	v, err := rtcs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (rtcs *ResourceTypeClassSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rtcs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = fmt.Errorf("ent: ResourceTypeClassSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) Float64X(ctx context.Context) float64 {
	v, err := rtcs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (rtcs *ResourceTypeClassSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(rtcs.fields) > 1 {
		return nil, errors.New("ent: ResourceTypeClassSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := rtcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) BoolsX(ctx context.Context) []bool {
	v, err := rtcs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (rtcs *ResourceTypeClassSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rtcs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{resourcetypeclass.Label}
	default:
		err = fmt.Errorf("ent: ResourceTypeClassSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rtcs *ResourceTypeClassSelect) BoolX(ctx context.Context) bool {
	v, err := rtcs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rtcs *ResourceTypeClassSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rtcs.fields {
		if !resourcetypeclass.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := rtcs.sqlQuery().Query()
	if err := rtcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rtcs *ResourceTypeClassSelect) sqlQuery() sql.Querier {
	selector := rtcs.sql
	selector.Select(selector.Columns(rtcs.fields...)...)
	return selector
}
