// Copyright (c) 2004-present Facebook All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebookincubator/symphony/pkg/ent/resourcetypebasetype"
)

// ResourceTypeBaseType is the model entity for the ResourceTypeBaseType schema.
type ResourceTypeBaseType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResourceTypeBaseTypeQuery when eager-loading is set.
	Edges ResourceTypeBaseTypeEdges `json:"edges"`
}

// ResourceTypeBaseTypeEdges holds the relations/edges for other nodes in the graph.
type ResourceTypeBaseTypeEdges struct {
	// ResourceBaseType holds the value of the resource_base_type edge.
	ResourceBaseType []*ResourceType
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ResourceBaseTypeOrErr returns the ResourceBaseType value or an error if the edge
// was not loaded in eager-loading.
func (e ResourceTypeBaseTypeEdges) ResourceBaseTypeOrErr() ([]*ResourceType, error) {
	if e.loadedTypes[0] {
		return e.ResourceBaseType, nil
	}
	return nil, &NotLoadedError{edge: "resource_base_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResourceTypeBaseType) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullTime{},   // create_time
		&sql.NullTime{},   // update_time
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResourceTypeBaseType fields.
func (rtbt *ResourceTypeBaseType) assignValues(values ...interface{}) error {
	if m, n := len(values), len(resourcetypebasetype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	rtbt.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field create_time", values[0])
	} else if value.Valid {
		rtbt.CreateTime = value.Time
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field update_time", values[1])
	} else if value.Valid {
		rtbt.UpdateTime = value.Time
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[2])
	} else if value.Valid {
		rtbt.Name = value.String
	}
	return nil
}

// QueryResourceBaseType queries the resource_base_type edge of the ResourceTypeBaseType.
func (rtbt *ResourceTypeBaseType) QueryResourceBaseType() *ResourceTypeQuery {
	return (&ResourceTypeBaseTypeClient{config: rtbt.config}).QueryResourceBaseType(rtbt)
}

// Update returns a builder for updating this ResourceTypeBaseType.
// Note that, you need to call ResourceTypeBaseType.Unwrap() before calling this method, if this ResourceTypeBaseType
// was returned from a transaction, and the transaction was committed or rolled back.
func (rtbt *ResourceTypeBaseType) Update() *ResourceTypeBaseTypeUpdateOne {
	return (&ResourceTypeBaseTypeClient{config: rtbt.config}).UpdateOne(rtbt)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (rtbt *ResourceTypeBaseType) Unwrap() *ResourceTypeBaseType {
	tx, ok := rtbt.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResourceTypeBaseType is not a transactional entity")
	}
	rtbt.config.driver = tx.drv
	return rtbt
}

// String implements the fmt.Stringer.
func (rtbt *ResourceTypeBaseType) String() string {
	var builder strings.Builder
	builder.WriteString("ResourceTypeBaseType(")
	builder.WriteString(fmt.Sprintf("id=%v", rtbt.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(rtbt.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(rtbt.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", name=")
	builder.WriteString(rtbt.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ResourceTypeBaseTypes is a parsable slice of ResourceTypeBaseType.
type ResourceTypeBaseTypes []*ResourceTypeBaseType

func (rtbt ResourceTypeBaseTypes) config(cfg config) {
	for _i := range rtbt {
		rtbt[_i].config = cfg
	}
}
