// Copyright (c) 2004-present Facebook All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebookincubator/symphony/pkg/ent/ruleactiontemplate"
)

// RuleActionTemplate is the model entity for the RuleActionTemplate schema.
type RuleActionTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RuleActionTemplate) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullTime{},   // create_time
		&sql.NullTime{},   // update_time
		&sql.NullString{}, // text
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RuleActionTemplate fields.
func (rat *RuleActionTemplate) assignValues(values ...interface{}) error {
	if m, n := len(values), len(ruleactiontemplate.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	rat.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field create_time", values[0])
	} else if value.Valid {
		rat.CreateTime = value.Time
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field update_time", values[1])
	} else if value.Valid {
		rat.UpdateTime = value.Time
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field text", values[2])
	} else if value.Valid {
		rat.Text = value.String
	}
	return nil
}

// Update returns a builder for updating this RuleActionTemplate.
// Note that, you need to call RuleActionTemplate.Unwrap() before calling this method, if this RuleActionTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (rat *RuleActionTemplate) Update() *RuleActionTemplateUpdateOne {
	return (&RuleActionTemplateClient{config: rat.config}).UpdateOne(rat)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (rat *RuleActionTemplate) Unwrap() *RuleActionTemplate {
	tx, ok := rat.config.driver.(*txDriver)
	if !ok {
		panic("ent: RuleActionTemplate is not a transactional entity")
	}
	rat.config.driver = tx.drv
	return rat
}

// String implements the fmt.Stringer.
func (rat *RuleActionTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("RuleActionTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v", rat.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(rat.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(rat.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", text=")
	builder.WriteString(rat.Text)
	builder.WriteByte(')')
	return builder.String()
}

// RuleActionTemplates is a parsable slice of RuleActionTemplate.
type RuleActionTemplates []*RuleActionTemplate

func (rat RuleActionTemplates) config(cfg config) {
	for _i := range rat {
		rat[_i].config = cfg
	}
}
