#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field
from datetime import datetime
from gql_client.runtime.datetime_utils import DATETIME_FIELD_METADATA
from gql_client.runtime.variables import encode_variables
from gql import gql, Client
from gql.transport.exceptions import TransportQueryError
from functools import partial
from numbers import Number
from typing import Any, AsyncGenerator, Callable, Dict, List, Generator, Optional
from time import perf_counter
from dataclasses_json import DataClassJsonMixin

# fmt: off
QUERY: List[str] = ["""
fragment PageInfoFragment on PageInfo {
  hasNextPage
  endCursor
}

"""]

@dataclass(frozen=True)
class PageInfoFragment(DataClassJsonMixin):
    hasNextPage: bool
    endCursor: Optional[str]
