name: Test Back
on:
  push:
    branches:
      - feature/devops_back_docomo
    paths-ignore:
      - infra/**
      - skaffold/**
      - tools/**
      - app/mobile/**

jobs:
  sonarqube:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0   
       - name: Sonar Scan
         run: |
               go version &&
               go test -coverprofile=coverage.out -covermode=count -json > report.json ./...
               exit 0
       - name: lista archivos
         run: ls -la && pwd
       - uses: sonarsource/sonarqube-scan-action@master 
         with:
             projectBaseDir: .
             args: >
               -Dsonar.projectKey=everisopennetworks_symphony
               -Dsonar.go.coverage.reportPaths=**/*coverage.out
               -Dsonar.go.tests.reportPaths=report.json      
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
       - name: SonarQube Quality Gate check
         uses: sonarsource/sonarqube-quality-gate-action@master
         timeout-minutes: 5
         env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         with:
           scanMetadataReportFile: .scannerwork/report-task.txt
           # Force to fail step after specific time
           timeout-minutes: 2
